// Livepeer Payments v1 — PayerDaemon service.
//
// The PayerDaemon runs next to a payer application (a specialized PayerApp —
// e.g., an OpenAI bridge or a Livepeer gateway). It creates and signs tickets,
// manages per-session sender nonces, and watches the payer's on-chain escrow.
//
// This service is mounted only when the daemon is started with
// `--mode=sender`. Calls to it in receiver mode return UNIMPLEMENTED.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: livepeer/payments/v1/payer_daemon.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayerDaemon_StartSession_FullMethodName   = "/livepeer.payments.v1.PayerDaemon/StartSession"
	PayerDaemon_CreatePayment_FullMethodName  = "/livepeer.payments.v1.PayerDaemon/CreatePayment"
	PayerDaemon_CloseSession_FullMethodName   = "/livepeer.payments.v1.PayerDaemon/CloseSession"
	PayerDaemon_GetDepositInfo_FullMethodName = "/livepeer.payments.v1.PayerDaemon/GetDepositInfo"
)

// PayerDaemonClient is the client API for PayerDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayerDaemonClient interface {
	// Start a new payment session against a given payee's advertised ticket
	// parameters. Returns a `work_id` that subsequent `CreatePayment` calls
	// reference. One session should cover one ongoing work relationship between
	// this payer and a specific payee (not one per HTTP call — amortize).
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// Create a payment blob (a `Payment` with one or more tickets) covering a
	// requested number of work units against an existing session. The returned
	// bytes are the exact wire-format `Payment` to hand to the payee.
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	// Close a session and free its nonce state.
	CloseSession(ctx context.Context, in *PayerDaemonCloseSessionRequest, opts ...grpc.CallOption) (*PayerDaemonCloseSessionResponse, error)
	// Inspect the payer's current TicketBroker deposit/reserve state. Read-only;
	// the daemon does not fund escrow.
	GetDepositInfo(ctx context.Context, in *GetDepositInfoRequest, opts ...grpc.CallOption) (*GetDepositInfoResponse, error)
}

type payerDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewPayerDaemonClient(cc grpc.ClientConnInterface) PayerDaemonClient {
	return &payerDaemonClient{cc}
}

func (c *payerDaemonClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payerDaemonClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payerDaemonClient) CloseSession(ctx context.Context, in *PayerDaemonCloseSessionRequest, opts ...grpc.CallOption) (*PayerDaemonCloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayerDaemonCloseSessionResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payerDaemonClient) GetDepositInfo(ctx context.Context, in *GetDepositInfoRequest, opts ...grpc.CallOption) (*GetDepositInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositInfoResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_GetDepositInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayerDaemonServer is the server API for PayerDaemon service.
// All implementations should embed UnimplementedPayerDaemonServer
// for forward compatibility.
type PayerDaemonServer interface {
	// Start a new payment session against a given payee's advertised ticket
	// parameters. Returns a `work_id` that subsequent `CreatePayment` calls
	// reference. One session should cover one ongoing work relationship between
	// this payer and a specific payee (not one per HTTP call — amortize).
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// Create a payment blob (a `Payment` with one or more tickets) covering a
	// requested number of work units against an existing session. The returned
	// bytes are the exact wire-format `Payment` to hand to the payee.
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	// Close a session and free its nonce state.
	CloseSession(context.Context, *PayerDaemonCloseSessionRequest) (*PayerDaemonCloseSessionResponse, error)
	// Inspect the payer's current TicketBroker deposit/reserve state. Read-only;
	// the daemon does not fund escrow.
	GetDepositInfo(context.Context, *GetDepositInfoRequest) (*GetDepositInfoResponse, error)
}

// UnimplementedPayerDaemonServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayerDaemonServer struct{}

func (UnimplementedPayerDaemonServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedPayerDaemonServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPayerDaemonServer) CloseSession(context.Context, *PayerDaemonCloseSessionRequest) (*PayerDaemonCloseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedPayerDaemonServer) GetDepositInfo(context.Context, *GetDepositInfoRequest) (*GetDepositInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositInfo not implemented")
}
func (UnimplementedPayerDaemonServer) testEmbeddedByValue() {}

// UnsafePayerDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayerDaemonServer will
// result in compilation errors.
type UnsafePayerDaemonServer interface {
	mustEmbedUnimplementedPayerDaemonServer()
}

func RegisterPayerDaemonServer(s grpc.ServiceRegistrar, srv PayerDaemonServer) {
	// If the following call pancis, it indicates UnimplementedPayerDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayerDaemon_ServiceDesc, srv)
}

func _PayerDaemon_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayerDaemon_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayerDaemon_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayerDaemonCloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).CloseSession(ctx, req.(*PayerDaemonCloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayerDaemon_GetDepositInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).GetDepositInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_GetDepositInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).GetDepositInfo(ctx, req.(*GetDepositInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayerDaemon_ServiceDesc is the grpc.ServiceDesc for PayerDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayerDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livepeer.payments.v1.PayerDaemon",
	HandlerType: (*PayerDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _PayerDaemon_StartSession_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _PayerDaemon_CreatePayment_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _PayerDaemon_CloseSession_Handler,
		},
		{
			MethodName: "GetDepositInfo",
			Handler:    _PayerDaemon_GetDepositInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livepeer/payments/v1/payer_daemon.proto",
}
