// Code generated by protoc-gen-go. DO NOT EDIT.
// source: livepeer/payments/v1/payee_daemon.proto

package paymentsv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRedemptionStatusResponse_Status int32

const (
	GetRedemptionStatusResponse_STATUS_UNSPECIFIED GetRedemptionStatusResponse_Status = 0
	GetRedemptionStatusResponse_STATUS_QUEUED      GetRedemptionStatusResponse_Status = 1
	GetRedemptionStatusResponse_STATUS_SUBMITTED   GetRedemptionStatusResponse_Status = 2
	GetRedemptionStatusResponse_STATUS_CONFIRMED   GetRedemptionStatusResponse_Status = 3
	GetRedemptionStatusResponse_STATUS_FAILED      GetRedemptionStatusResponse_Status = 4
)

var GetRedemptionStatusResponse_Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_QUEUED",
	2: "STATUS_SUBMITTED",
	3: "STATUS_CONFIRMED",
	4: "STATUS_FAILED",
}

var GetRedemptionStatusResponse_Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_QUEUED":      1,
	"STATUS_SUBMITTED":   2,
	"STATUS_CONFIRMED":   3,
	"STATUS_FAILED":      4,
}

func (x GetRedemptionStatusResponse_Status) String() string {
	return proto.EnumName(GetRedemptionStatusResponse_Status_name, int32(x))
}

func (GetRedemptionStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{20, 0}
}

type GetQuoteRequest struct {
	// ETH address of the sender asking for a quote.
	Sender []byte `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Capability the sender intends to purchase. The daemon maps this to the
	// `PriceInfo.capability` uint32 at the wire boundary. One capability may
	// host many models; the response lists them all.
	Capability           string   `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetQuoteRequest) Reset()         { *m = GetQuoteRequest{} }
func (m *GetQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*GetQuoteRequest) ProtoMessage()    {}
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{0}
}

func (m *GetQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuoteRequest.Unmarshal(m, b)
}
func (m *GetQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuoteRequest.Marshal(b, m, deterministic)
}
func (m *GetQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuoteRequest.Merge(m, src)
}
func (m *GetQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_GetQuoteRequest.Size(m)
}
func (m *GetQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuoteRequest proto.InternalMessageInfo

func (m *GetQuoteRequest) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *GetQuoteRequest) GetCapability() string {
	if m != nil {
		return m.Capability
	}
	return ""
}

type GetQuoteResponse struct {
	// Single TicketParams for this (sender, capability). Face value is sized
	// to cover the most expensive model on this capability so one session
	// covers the whole model set without re-keying RecipientRandHash per
	// model.
	TicketParams *TicketParams `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// Per-model pricing. Ordered by model name for deterministic comparison
	// on the bridge's quote-refresh cycle. Empty iff the daemon has no
	// models configured for this capability (caller should treat as NotFound).
	ModelPrices          []*ModelPrice `protobuf:"bytes,2,rep,name=model_prices,json=modelPrices,proto3" json:"model_prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetQuoteResponse) Reset()         { *m = GetQuoteResponse{} }
func (m *GetQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*GetQuoteResponse) ProtoMessage()    {}
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{1}
}

func (m *GetQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuoteResponse.Unmarshal(m, b)
}
func (m *GetQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuoteResponse.Marshal(b, m, deterministic)
}
func (m *GetQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuoteResponse.Merge(m, src)
}
func (m *GetQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_GetQuoteResponse.Size(m)
}
func (m *GetQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuoteResponse proto.InternalMessageInfo

func (m *GetQuoteResponse) GetTicketParams() *TicketParams {
	if m != nil {
		return m.TicketParams
	}
	return nil
}

func (m *GetQuoteResponse) GetModelPrices() []*ModelPrice {
	if m != nil {
		return m.ModelPrices
	}
	return nil
}

// ModelPrice pairs a model identifier with its wei-per-work-unit price.
// Shared between GetQuoteResponse and ListCapabilitiesResponse so the two
// surfaces cannot drift.
type ModelPrice struct {
	// Model identifier, e.g. "llama-3.3-70b". Must match the model string the
	// bridge uses when resolving a request to a node.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Price for one work unit (see CapabilityEntry.work_unit for the meaning
	// of "unit" on this capability).
	PriceInfo            *PriceInfo `protobuf:"bytes,2,opt,name=price_info,json=priceInfo,proto3" json:"price_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ModelPrice) Reset()         { *m = ModelPrice{} }
func (m *ModelPrice) String() string { return proto.CompactTextString(m) }
func (*ModelPrice) ProtoMessage()    {}
func (*ModelPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{2}
}

func (m *ModelPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelPrice.Unmarshal(m, b)
}
func (m *ModelPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelPrice.Marshal(b, m, deterministic)
}
func (m *ModelPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelPrice.Merge(m, src)
}
func (m *ModelPrice) XXX_Size() int {
	return xxx_messageInfo_ModelPrice.Size(m)
}
func (m *ModelPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelPrice.DiscardUnknown(m)
}

var xxx_messageInfo_ModelPrice proto.InternalMessageInfo

func (m *ModelPrice) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *ModelPrice) GetPriceInfo() *PriceInfo {
	if m != nil {
		return m.PriceInfo
	}
	return nil
}

type ListCapabilitiesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCapabilitiesRequest) Reset()         { *m = ListCapabilitiesRequest{} }
func (m *ListCapabilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCapabilitiesRequest) ProtoMessage()    {}
func (*ListCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{3}
}

func (m *ListCapabilitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCapabilitiesRequest.Unmarshal(m, b)
}
func (m *ListCapabilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCapabilitiesRequest.Marshal(b, m, deterministic)
}
func (m *ListCapabilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCapabilitiesRequest.Merge(m, src)
}
func (m *ListCapabilitiesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCapabilitiesRequest.Size(m)
}
func (m *ListCapabilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCapabilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCapabilitiesRequest proto.InternalMessageInfo

type ListCapabilitiesResponse struct {
	// Matches `protocol_version` in the shared worker.yaml. Worker-node uses
	// this to detect daemon/worker version skew before comparing payload.
	ProtocolVersion int32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Full capability catalog as parsed by the daemon at startup. Ordered
	// by capability string, then model name, for deterministic comparison.
	Capabilities         []*CapabilityEntry `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListCapabilitiesResponse) Reset()         { *m = ListCapabilitiesResponse{} }
func (m *ListCapabilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCapabilitiesResponse) ProtoMessage()    {}
func (*ListCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{4}
}

func (m *ListCapabilitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCapabilitiesResponse.Unmarshal(m, b)
}
func (m *ListCapabilitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCapabilitiesResponse.Marshal(b, m, deterministic)
}
func (m *ListCapabilitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCapabilitiesResponse.Merge(m, src)
}
func (m *ListCapabilitiesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCapabilitiesResponse.Size(m)
}
func (m *ListCapabilitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCapabilitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCapabilitiesResponse proto.InternalMessageInfo

func (m *ListCapabilitiesResponse) GetProtocolVersion() int32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *ListCapabilitiesResponse) GetCapabilities() []*CapabilityEntry {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type CapabilityEntry struct {
	// Capability string in the canonical form `openai:<uri-path>` for the
	// OpenAI module family; other modules use their own domain prefix
	// (e.g. `transcoding:...`). Opaque to the daemon.
	Capability string `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	// Work-unit identifier for observability ("token", "audio_second",
	// "image_step_megapixel", "character", ...). The daemon treats work
	// units as opaque int64 — this field is metadata for the worker /
	// bridge.
	WorkUnit string `protobuf:"bytes,2,opt,name=work_unit,json=workUnit,proto3" json:"work_unit,omitempty"`
	// Models served on this capability, with their configured prices.
	Models               []*ModelPrice `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CapabilityEntry) Reset()         { *m = CapabilityEntry{} }
func (m *CapabilityEntry) String() string { return proto.CompactTextString(m) }
func (*CapabilityEntry) ProtoMessage()    {}
func (*CapabilityEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{5}
}

func (m *CapabilityEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapabilityEntry.Unmarshal(m, b)
}
func (m *CapabilityEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapabilityEntry.Marshal(b, m, deterministic)
}
func (m *CapabilityEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapabilityEntry.Merge(m, src)
}
func (m *CapabilityEntry) XXX_Size() int {
	return xxx_messageInfo_CapabilityEntry.Size(m)
}
func (m *CapabilityEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CapabilityEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CapabilityEntry proto.InternalMessageInfo

func (m *CapabilityEntry) GetCapability() string {
	if m != nil {
		return m.Capability
	}
	return ""
}

func (m *CapabilityEntry) GetWorkUnit() string {
	if m != nil {
		return m.WorkUnit
	}
	return ""
}

func (m *CapabilityEntry) GetModels() []*ModelPrice {
	if m != nil {
		return m.Models
	}
	return nil
}

type ProcessPaymentRequest struct {
	// Wire-format `livepeer.payments.v1.Payment` bytes, exactly as received
	// from the sender.
	PaymentBytes []byte `protobuf:"bytes,1,opt,name=payment_bytes,json=paymentBytes,proto3" json:"payment_bytes,omitempty"`
	// Opaque session identifier chosen by the payee app. The daemon uses this
	// as the balance key.
	WorkId               string   `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessPaymentRequest) Reset()         { *m = ProcessPaymentRequest{} }
func (m *ProcessPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessPaymentRequest) ProtoMessage()    {}
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{6}
}

func (m *ProcessPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessPaymentRequest.Unmarshal(m, b)
}
func (m *ProcessPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessPaymentRequest.Marshal(b, m, deterministic)
}
func (m *ProcessPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessPaymentRequest.Merge(m, src)
}
func (m *ProcessPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessPaymentRequest.Size(m)
}
func (m *ProcessPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessPaymentRequest proto.InternalMessageInfo

func (m *ProcessPaymentRequest) GetPaymentBytes() []byte {
	if m != nil {
		return m.PaymentBytes
	}
	return nil
}

func (m *ProcessPaymentRequest) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

type ProcessPaymentResponse struct {
	// Sender address extracted from the validated payment.
	Sender []byte `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Expected value credited to the sender's balance by this payment (wei,
	// big-endian bytes).
	CreditedEv []byte `protobuf:"bytes,2,opt,name=credited_ev,json=creditedEv,proto3" json:"credited_ev,omitempty"`
	// New balance after crediting (wei, big-endian bytes).
	Balance []byte `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	// Number of tickets in this payment that were identified as winners and
	// queued for on-chain redemption.
	WinnersQueued        int32    `protobuf:"varint,4,opt,name=winners_queued,json=winnersQueued,proto3" json:"winners_queued,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessPaymentResponse) Reset()         { *m = ProcessPaymentResponse{} }
func (m *ProcessPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessPaymentResponse) ProtoMessage()    {}
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{7}
}

func (m *ProcessPaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessPaymentResponse.Unmarshal(m, b)
}
func (m *ProcessPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessPaymentResponse.Marshal(b, m, deterministic)
}
func (m *ProcessPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessPaymentResponse.Merge(m, src)
}
func (m *ProcessPaymentResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessPaymentResponse.Size(m)
}
func (m *ProcessPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessPaymentResponse proto.InternalMessageInfo

func (m *ProcessPaymentResponse) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *ProcessPaymentResponse) GetCreditedEv() []byte {
	if m != nil {
		return m.CreditedEv
	}
	return nil
}

func (m *ProcessPaymentResponse) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *ProcessPaymentResponse) GetWinnersQueued() int32 {
	if m != nil {
		return m.WinnersQueued
	}
	return 0
}

type DebitBalanceRequest struct {
	// Sender whose balance is being debited.
	Sender []byte `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// Work session whose balance is being debited.
	WorkId string `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	// Number of work units actually consumed.
	WorkUnits            int64    `protobuf:"varint,3,opt,name=work_units,json=workUnits,proto3" json:"work_units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebitBalanceRequest) Reset()         { *m = DebitBalanceRequest{} }
func (m *DebitBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*DebitBalanceRequest) ProtoMessage()    {}
func (*DebitBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{8}
}

func (m *DebitBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebitBalanceRequest.Unmarshal(m, b)
}
func (m *DebitBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebitBalanceRequest.Marshal(b, m, deterministic)
}
func (m *DebitBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebitBalanceRequest.Merge(m, src)
}
func (m *DebitBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_DebitBalanceRequest.Size(m)
}
func (m *DebitBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebitBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebitBalanceRequest proto.InternalMessageInfo

func (m *DebitBalanceRequest) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *DebitBalanceRequest) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

func (m *DebitBalanceRequest) GetWorkUnits() int64 {
	if m != nil {
		return m.WorkUnits
	}
	return 0
}

type DebitBalanceResponse struct {
	// New balance after debit (wei, big-endian bytes). Negative values indicate
	// overdraft; callers should stop serving work when this happens.
	Balance              []byte   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebitBalanceResponse) Reset()         { *m = DebitBalanceResponse{} }
func (m *DebitBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*DebitBalanceResponse) ProtoMessage()    {}
func (*DebitBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{9}
}

func (m *DebitBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebitBalanceResponse.Unmarshal(m, b)
}
func (m *DebitBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebitBalanceResponse.Marshal(b, m, deterministic)
}
func (m *DebitBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebitBalanceResponse.Merge(m, src)
}
func (m *DebitBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_DebitBalanceResponse.Size(m)
}
func (m *DebitBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DebitBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DebitBalanceResponse proto.InternalMessageInfo

func (m *DebitBalanceResponse) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

type SufficientBalanceRequest struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WorkId               string   `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	MinWorkUnits         int64    `protobuf:"varint,3,opt,name=min_work_units,json=minWorkUnits,proto3" json:"min_work_units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SufficientBalanceRequest) Reset()         { *m = SufficientBalanceRequest{} }
func (m *SufficientBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*SufficientBalanceRequest) ProtoMessage()    {}
func (*SufficientBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{10}
}

func (m *SufficientBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SufficientBalanceRequest.Unmarshal(m, b)
}
func (m *SufficientBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SufficientBalanceRequest.Marshal(b, m, deterministic)
}
func (m *SufficientBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SufficientBalanceRequest.Merge(m, src)
}
func (m *SufficientBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_SufficientBalanceRequest.Size(m)
}
func (m *SufficientBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SufficientBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SufficientBalanceRequest proto.InternalMessageInfo

func (m *SufficientBalanceRequest) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *SufficientBalanceRequest) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

func (m *SufficientBalanceRequest) GetMinWorkUnits() int64 {
	if m != nil {
		return m.MinWorkUnits
	}
	return 0
}

type SufficientBalanceResponse struct {
	Sufficient bool `protobuf:"varint,1,opt,name=sufficient,proto3" json:"sufficient,omitempty"`
	// Current balance (wei, big-endian bytes).
	Balance              []byte   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SufficientBalanceResponse) Reset()         { *m = SufficientBalanceResponse{} }
func (m *SufficientBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*SufficientBalanceResponse) ProtoMessage()    {}
func (*SufficientBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{11}
}

func (m *SufficientBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SufficientBalanceResponse.Unmarshal(m, b)
}
func (m *SufficientBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SufficientBalanceResponse.Marshal(b, m, deterministic)
}
func (m *SufficientBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SufficientBalanceResponse.Merge(m, src)
}
func (m *SufficientBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_SufficientBalanceResponse.Size(m)
}
func (m *SufficientBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SufficientBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SufficientBalanceResponse proto.InternalMessageInfo

func (m *SufficientBalanceResponse) GetSufficient() bool {
	if m != nil {
		return m.Sufficient
	}
	return false
}

func (m *SufficientBalanceResponse) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

type GetBalanceRequest struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WorkId               string   `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{12}
}

func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(m, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *GetBalanceRequest) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

type GetBalanceResponse struct {
	Balance              []byte   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{13}
}

func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(m, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

type PayeeDaemonCloseSessionRequest struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	WorkId               string   `protobuf:"bytes,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayeeDaemonCloseSessionRequest) Reset()         { *m = PayeeDaemonCloseSessionRequest{} }
func (m *PayeeDaemonCloseSessionRequest) String() string { return proto.CompactTextString(m) }
func (*PayeeDaemonCloseSessionRequest) ProtoMessage()    {}
func (*PayeeDaemonCloseSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{14}
}

func (m *PayeeDaemonCloseSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayeeDaemonCloseSessionRequest.Unmarshal(m, b)
}
func (m *PayeeDaemonCloseSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayeeDaemonCloseSessionRequest.Marshal(b, m, deterministic)
}
func (m *PayeeDaemonCloseSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayeeDaemonCloseSessionRequest.Merge(m, src)
}
func (m *PayeeDaemonCloseSessionRequest) XXX_Size() int {
	return xxx_messageInfo_PayeeDaemonCloseSessionRequest.Size(m)
}
func (m *PayeeDaemonCloseSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayeeDaemonCloseSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayeeDaemonCloseSessionRequest proto.InternalMessageInfo

func (m *PayeeDaemonCloseSessionRequest) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *PayeeDaemonCloseSessionRequest) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

type PayeeDaemonCloseSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayeeDaemonCloseSessionResponse) Reset()         { *m = PayeeDaemonCloseSessionResponse{} }
func (m *PayeeDaemonCloseSessionResponse) String() string { return proto.CompactTextString(m) }
func (*PayeeDaemonCloseSessionResponse) ProtoMessage()    {}
func (*PayeeDaemonCloseSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{15}
}

func (m *PayeeDaemonCloseSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayeeDaemonCloseSessionResponse.Unmarshal(m, b)
}
func (m *PayeeDaemonCloseSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayeeDaemonCloseSessionResponse.Marshal(b, m, deterministic)
}
func (m *PayeeDaemonCloseSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayeeDaemonCloseSessionResponse.Merge(m, src)
}
func (m *PayeeDaemonCloseSessionResponse) XXX_Size() int {
	return xxx_messageInfo_PayeeDaemonCloseSessionResponse.Size(m)
}
func (m *PayeeDaemonCloseSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayeeDaemonCloseSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayeeDaemonCloseSessionResponse proto.InternalMessageInfo

type ListPendingRedemptionsRequest struct {
	// Optional: filter to tickets queued on or after this Unix epoch seconds.
	Since                int64    `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPendingRedemptionsRequest) Reset()         { *m = ListPendingRedemptionsRequest{} }
func (m *ListPendingRedemptionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPendingRedemptionsRequest) ProtoMessage()    {}
func (*ListPendingRedemptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{16}
}

func (m *ListPendingRedemptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPendingRedemptionsRequest.Unmarshal(m, b)
}
func (m *ListPendingRedemptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPendingRedemptionsRequest.Marshal(b, m, deterministic)
}
func (m *ListPendingRedemptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPendingRedemptionsRequest.Merge(m, src)
}
func (m *ListPendingRedemptionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPendingRedemptionsRequest.Size(m)
}
func (m *ListPendingRedemptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPendingRedemptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPendingRedemptionsRequest proto.InternalMessageInfo

func (m *ListPendingRedemptionsRequest) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

type ListPendingRedemptionsResponse struct {
	Redemptions          []*PendingRedemption `protobuf:"bytes,1,rep,name=redemptions,proto3" json:"redemptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListPendingRedemptionsResponse) Reset()         { *m = ListPendingRedemptionsResponse{} }
func (m *ListPendingRedemptionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPendingRedemptionsResponse) ProtoMessage()    {}
func (*ListPendingRedemptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{17}
}

func (m *ListPendingRedemptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPendingRedemptionsResponse.Unmarshal(m, b)
}
func (m *ListPendingRedemptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPendingRedemptionsResponse.Marshal(b, m, deterministic)
}
func (m *ListPendingRedemptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPendingRedemptionsResponse.Merge(m, src)
}
func (m *ListPendingRedemptionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPendingRedemptionsResponse.Size(m)
}
func (m *ListPendingRedemptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPendingRedemptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPendingRedemptionsResponse proto.InternalMessageInfo

func (m *ListPendingRedemptionsResponse) GetRedemptions() []*PendingRedemption {
	if m != nil {
		return m.Redemptions
	}
	return nil
}

type PendingRedemption struct {
	// Deterministic ticket identifier (keccak256 of the ticket hash).
	TicketHash []byte `protobuf:"bytes,1,opt,name=ticket_hash,json=ticketHash,proto3" json:"ticket_hash,omitempty"`
	Sender     []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Face value (wei, big-endian bytes).
	FaceValue []byte `protobuf:"bytes,3,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Unix epoch seconds when the ticket was queued.
	QueuedAt int64 `protobuf:"varint,4,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	// Number of on-chain redemption attempts made so far.
	Attempts             int32    `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingRedemption) Reset()         { *m = PendingRedemption{} }
func (m *PendingRedemption) String() string { return proto.CompactTextString(m) }
func (*PendingRedemption) ProtoMessage()    {}
func (*PendingRedemption) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{18}
}

func (m *PendingRedemption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingRedemption.Unmarshal(m, b)
}
func (m *PendingRedemption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingRedemption.Marshal(b, m, deterministic)
}
func (m *PendingRedemption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingRedemption.Merge(m, src)
}
func (m *PendingRedemption) XXX_Size() int {
	return xxx_messageInfo_PendingRedemption.Size(m)
}
func (m *PendingRedemption) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingRedemption.DiscardUnknown(m)
}

var xxx_messageInfo_PendingRedemption proto.InternalMessageInfo

func (m *PendingRedemption) GetTicketHash() []byte {
	if m != nil {
		return m.TicketHash
	}
	return nil
}

func (m *PendingRedemption) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *PendingRedemption) GetFaceValue() []byte {
	if m != nil {
		return m.FaceValue
	}
	return nil
}

func (m *PendingRedemption) GetQueuedAt() int64 {
	if m != nil {
		return m.QueuedAt
	}
	return 0
}

func (m *PendingRedemption) GetAttempts() int32 {
	if m != nil {
		return m.Attempts
	}
	return 0
}

type GetRedemptionStatusRequest struct {
	TicketHash           []byte   `protobuf:"bytes,1,opt,name=ticket_hash,json=ticketHash,proto3" json:"ticket_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRedemptionStatusRequest) Reset()         { *m = GetRedemptionStatusRequest{} }
func (m *GetRedemptionStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetRedemptionStatusRequest) ProtoMessage()    {}
func (*GetRedemptionStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{19}
}

func (m *GetRedemptionStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedemptionStatusRequest.Unmarshal(m, b)
}
func (m *GetRedemptionStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedemptionStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetRedemptionStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedemptionStatusRequest.Merge(m, src)
}
func (m *GetRedemptionStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetRedemptionStatusRequest.Size(m)
}
func (m *GetRedemptionStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedemptionStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedemptionStatusRequest proto.InternalMessageInfo

func (m *GetRedemptionStatusRequest) GetTicketHash() []byte {
	if m != nil {
		return m.TicketHash
	}
	return nil
}

type GetRedemptionStatusResponse struct {
	Status GetRedemptionStatusResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=livepeer.payments.v1.GetRedemptionStatusResponse_Status" json:"status,omitempty"`
	// Transaction hash once submitted; empty before then.
	TxHash []byte `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Non-empty when status is STATUS_FAILED — operator-actionable message.
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRedemptionStatusResponse) Reset()         { *m = GetRedemptionStatusResponse{} }
func (m *GetRedemptionStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetRedemptionStatusResponse) ProtoMessage()    {}
func (*GetRedemptionStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_670c5d699b60b606, []int{20}
}

func (m *GetRedemptionStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedemptionStatusResponse.Unmarshal(m, b)
}
func (m *GetRedemptionStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedemptionStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetRedemptionStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedemptionStatusResponse.Merge(m, src)
}
func (m *GetRedemptionStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetRedemptionStatusResponse.Size(m)
}
func (m *GetRedemptionStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedemptionStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedemptionStatusResponse proto.InternalMessageInfo

func (m *GetRedemptionStatusResponse) GetStatus() GetRedemptionStatusResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetRedemptionStatusResponse_STATUS_UNSPECIFIED
}

func (m *GetRedemptionStatusResponse) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *GetRedemptionStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("livepeer.payments.v1.GetRedemptionStatusResponse_Status", GetRedemptionStatusResponse_Status_name, GetRedemptionStatusResponse_Status_value)
	proto.RegisterType((*GetQuoteRequest)(nil), "livepeer.payments.v1.GetQuoteRequest")
	proto.RegisterType((*GetQuoteResponse)(nil), "livepeer.payments.v1.GetQuoteResponse")
	proto.RegisterType((*ModelPrice)(nil), "livepeer.payments.v1.ModelPrice")
	proto.RegisterType((*ListCapabilitiesRequest)(nil), "livepeer.payments.v1.ListCapabilitiesRequest")
	proto.RegisterType((*ListCapabilitiesResponse)(nil), "livepeer.payments.v1.ListCapabilitiesResponse")
	proto.RegisterType((*CapabilityEntry)(nil), "livepeer.payments.v1.CapabilityEntry")
	proto.RegisterType((*ProcessPaymentRequest)(nil), "livepeer.payments.v1.ProcessPaymentRequest")
	proto.RegisterType((*ProcessPaymentResponse)(nil), "livepeer.payments.v1.ProcessPaymentResponse")
	proto.RegisterType((*DebitBalanceRequest)(nil), "livepeer.payments.v1.DebitBalanceRequest")
	proto.RegisterType((*DebitBalanceResponse)(nil), "livepeer.payments.v1.DebitBalanceResponse")
	proto.RegisterType((*SufficientBalanceRequest)(nil), "livepeer.payments.v1.SufficientBalanceRequest")
	proto.RegisterType((*SufficientBalanceResponse)(nil), "livepeer.payments.v1.SufficientBalanceResponse")
	proto.RegisterType((*GetBalanceRequest)(nil), "livepeer.payments.v1.GetBalanceRequest")
	proto.RegisterType((*GetBalanceResponse)(nil), "livepeer.payments.v1.GetBalanceResponse")
	proto.RegisterType((*PayeeDaemonCloseSessionRequest)(nil), "livepeer.payments.v1.PayeeDaemonCloseSessionRequest")
	proto.RegisterType((*PayeeDaemonCloseSessionResponse)(nil), "livepeer.payments.v1.PayeeDaemonCloseSessionResponse")
	proto.RegisterType((*ListPendingRedemptionsRequest)(nil), "livepeer.payments.v1.ListPendingRedemptionsRequest")
	proto.RegisterType((*ListPendingRedemptionsResponse)(nil), "livepeer.payments.v1.ListPendingRedemptionsResponse")
	proto.RegisterType((*PendingRedemption)(nil), "livepeer.payments.v1.PendingRedemption")
	proto.RegisterType((*GetRedemptionStatusRequest)(nil), "livepeer.payments.v1.GetRedemptionStatusRequest")
	proto.RegisterType((*GetRedemptionStatusResponse)(nil), "livepeer.payments.v1.GetRedemptionStatusResponse")
}

func init() {
	proto.RegisterFile("livepeer/payments/v1/payee_daemon.proto", fileDescriptor_670c5d699b60b606)
}

var fileDescriptor_670c5d699b60b606 = []byte{
	// 1146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xef, 0x4f, 0xdb, 0x46,
	0x18, 0x9e, 0x93, 0x92, 0x26, 0x6f, 0x02, 0x0d, 0x57, 0x46, 0xd3, 0x54, 0xa5, 0xcc, 0x1b, 0x83,
	0x6e, 0x4b, 0x52, 0x68, 0x2b, 0x55, 0x9a, 0x36, 0x09, 0x92, 0xc0, 0x22, 0x95, 0x2e, 0x38, 0xa4,
	0xd3, 0xf6, 0xc5, 0x72, 0xec, 0x97, 0x72, 0x23, 0xb1, 0x8d, 0xef, 0x9c, 0x36, 0xdb, 0xc7, 0x69,
	0xd2, 0x3e, 0x4e, 0xfd, 0x0b, 0xf6, 0x61, 0x7f, 0xe8, 0xe4, 0xf3, 0x39, 0x38, 0xc1, 0x2e, 0xb0,
	0x7e, 0xf3, 0xfb, 0xdc, 0xfb, 0xe3, 0xb9, 0xe7, 0xee, 0xde, 0x3b, 0xc3, 0xe6, 0x90, 0x8e, 0xd1,
	0x45, 0xf4, 0x1a, 0xae, 0x31, 0x19, 0xa1, 0xcd, 0x59, 0x63, 0xbc, 0x1d, 0x7c, 0x23, 0xea, 0x96,
	0x81, 0x23, 0xc7, 0xae, 0xbb, 0x9e, 0xc3, 0x1d, 0xb2, 0x12, 0x39, 0xd6, 0x23, 0xc7, 0xfa, 0x78,
	0xbb, 0xba, 0x9e, 0x18, 0xce, 0x27, 0x2e, 0xb2, 0x30, 0x4e, 0xed, 0xc0, 0x9d, 0x03, 0xe4, 0x47,
	0xbe, 0xc3, 0x51, 0xc3, 0x73, 0x1f, 0x19, 0x27, 0xab, 0x90, 0x63, 0x68, 0x5b, 0xe8, 0x55, 0x94,
	0x75, 0x65, 0xab, 0xa4, 0x49, 0x8b, 0xac, 0x01, 0x98, 0x86, 0x6b, 0x0c, 0xe8, 0x90, 0xf2, 0x49,
	0x25, 0xb3, 0xae, 0x6c, 0x15, 0xb4, 0x18, 0xa2, 0xfe, 0xa3, 0x40, 0xf9, 0x22, 0x17, 0x73, 0x1d,
	0x9b, 0x21, 0x39, 0x80, 0x45, 0x4e, 0xcd, 0x33, 0xe4, 0xba, 0x6b, 0x78, 0xc6, 0x88, 0x89, 0x9c,
	0xc5, 0x1d, 0xb5, 0x9e, 0xc4, 0xb7, 0x7e, 0x2c, 0x5c, 0xbb, 0xc2, 0x53, 0x2b, 0xf1, 0x98, 0x45,
	0x9a, 0x50, 0x1a, 0x39, 0x16, 0x0e, 0x75, 0xd7, 0xa3, 0x26, 0xb2, 0x4a, 0x66, 0x3d, 0xbb, 0x55,
	0xdc, 0x59, 0x4f, 0xce, 0x73, 0x18, 0x78, 0x76, 0x03, 0x47, 0xad, 0x38, 0x9a, 0x7e, 0x33, 0x75,
	0x00, 0x70, 0x31, 0x44, 0x56, 0x60, 0x41, 0x0c, 0x0a, 0x4e, 0x05, 0x2d, 0x34, 0xc8, 0xf7, 0x00,
	0xa2, 0x84, 0x4e, 0xed, 0x13, 0x47, 0x4c, 0xb3, 0xb8, 0xf3, 0x28, 0xb9, 0x8c, 0x48, 0xd3, 0xb1,
	0x4f, 0x1c, 0xad, 0xe0, 0x46, 0x9f, 0xea, 0x7d, 0xb8, 0xf7, 0x92, 0x32, 0xde, 0x8c, 0x84, 0xa1,
	0xc8, 0xa4, 0xb2, 0xea, 0xdf, 0x0a, 0x54, 0x2e, 0x8f, 0x49, 0xa5, 0x1e, 0x43, 0x59, 0x2c, 0x89,
	0xe9, 0x0c, 0xf5, 0x31, 0x7a, 0x8c, 0x3a, 0xb6, 0x20, 0xb6, 0xa0, 0xdd, 0x89, 0xf0, 0xd7, 0x21,
	0x4c, 0x3a, 0x50, 0x32, 0x63, 0x29, 0xa4, 0x16, 0x1b, 0xc9, 0x24, 0xa7, 0xc5, 0x26, 0x6d, 0x9b,
	0x7b, 0x13, 0x6d, 0x26, 0x54, 0xfd, 0x4b, 0x81, 0x3b, 0x73, 0x1e, 0x73, 0x0b, 0xad, 0xcc, 0x2f,
	0x34, 0x79, 0x00, 0x85, 0xb7, 0x8e, 0x77, 0xa6, 0xfb, 0x36, 0xe5, 0x72, 0x1f, 0xe4, 0x03, 0xa0,
	0x6f, 0x53, 0x4e, 0x5e, 0x40, 0x4e, 0xe8, 0xc8, 0x2a, 0xd9, 0x6b, 0xae, 0x90, 0xf4, 0x57, 0xfb,
	0xf0, 0x69, 0xd7, 0x73, 0x4c, 0x64, 0xac, 0x1b, 0x3a, 0x46, 0x1b, 0xf2, 0x73, 0x58, 0x94, 0xa1,
	0xfa, 0x60, 0xc2, 0x91, 0xc9, 0x7d, 0x59, 0x92, 0xe0, 0x5e, 0x80, 0x91, 0x7b, 0x70, 0x5b, 0x90,
	0xa2, 0x96, 0xa4, 0x94, 0x0b, 0xcc, 0x8e, 0xa5, 0xbe, 0x57, 0x60, 0x75, 0x3e, 0xaf, 0x94, 0x3c,
	0x6d, 0xa7, 0x3f, 0x82, 0xa2, 0xe9, 0xa1, 0x45, 0x39, 0x5a, 0x3a, 0x8e, 0x45, 0xbe, 0x92, 0x06,
	0x11, 0xd4, 0x1e, 0x93, 0x0a, 0xdc, 0x1e, 0x18, 0x43, 0xc3, 0x36, 0xb1, 0x92, 0x15, 0x83, 0x91,
	0x49, 0x36, 0x60, 0xe9, 0x2d, 0xb5, 0x6d, 0xf4, 0x98, 0x7e, 0xee, 0xa3, 0x8f, 0x56, 0xe5, 0x96,
	0x58, 0xc3, 0x45, 0x89, 0x1e, 0x09, 0x50, 0x45, 0xb8, 0xdb, 0xc2, 0x01, 0xe5, 0x7b, 0x61, 0xd8,
	0x55, 0x47, 0x2f, 0x6d, 0x72, 0xe4, 0x21, 0xc0, 0x74, 0x29, 0x98, 0xe0, 0x92, 0xd5, 0x0a, 0xd1,
	0x5a, 0x30, 0xf5, 0x09, 0xac, 0xcc, 0x96, 0x91, 0x13, 0x8f, 0xf1, 0x57, 0x66, 0xf8, 0xab, 0xe7,
	0x50, 0xe9, 0xf9, 0x27, 0x27, 0xd4, 0xa4, 0x81, 0xb2, 0x1f, 0xc9, 0xee, 0x0b, 0x58, 0x1a, 0x51,
	0x5b, 0xbf, 0xc4, 0xb0, 0x34, 0xa2, 0xf6, 0x4f, 0x53, 0x92, 0x7d, 0xb8, 0x9f, 0x50, 0x52, 0x32,
	0x5d, 0x03, 0x60, 0xd3, 0x41, 0x51, 0x37, 0xaf, 0xc5, 0x90, 0xf8, 0x4c, 0x32, 0xb3, 0x33, 0x69,
	0xc1, 0xf2, 0x01, 0x7e, 0xec, 0x14, 0xd4, 0x3a, 0x90, 0x78, 0x96, 0x2b, 0xf5, 0x3b, 0x82, 0xb5,
	0x6e, 0xd0, 0x9d, 0x5b, 0xa2, 0x39, 0x37, 0x87, 0x0e, 0xc3, 0x1e, 0xb2, 0xe0, 0xd4, 0xfe, 0x6f,
	0x0a, 0x9f, 0xc1, 0xa3, 0xd4, 0x94, 0x21, 0x1f, 0xf5, 0x39, 0x3c, 0x0c, 0xfa, 0x4a, 0x17, 0x6d,
	0x8b, 0xda, 0x6f, 0x34, 0xb4, 0x70, 0xe4, 0x72, 0xea, 0xd8, 0x51, 0xe7, 0x09, 0x5a, 0x1d, 0xa3,
	0x11, 0xdd, 0xac, 0x16, 0x1a, 0xea, 0x19, 0xac, 0xa5, 0x85, 0xc9, 0x89, 0x76, 0xa0, 0xe8, 0x5d,
	0xc0, 0x15, 0x45, 0x1c, 0xe9, 0xcd, 0x94, 0x6e, 0x38, 0x9f, 0x46, 0x8b, 0xc7, 0xaa, 0xff, 0x2a,
	0xb0, 0x7c, 0xc9, 0x25, 0x38, 0x6a, 0xf2, 0x7e, 0x38, 0x35, 0xd8, 0xa9, 0x94, 0x04, 0x42, 0xe8,
	0x07, 0x83, 0x9d, 0xc6, 0xe4, 0xca, 0xcc, 0xc8, 0xf5, 0x10, 0xe0, 0xc4, 0x30, 0x51, 0x1f, 0x1b,
	0x43, 0x3f, 0x3a, 0x85, 0x85, 0x00, 0x79, 0x1d, 0x00, 0x41, 0x8f, 0x0a, 0xcf, 0x9f, 0x6e, 0x70,
	0x71, 0x04, 0xb3, 0x5a, 0x3e, 0x04, 0x76, 0x39, 0xa9, 0x42, 0xde, 0xe0, 0x3c, 0xa0, 0xc0, 0x2a,
	0x0b, 0xe2, 0x78, 0x4e, 0x6d, 0xf5, 0x3b, 0xa8, 0x1e, 0x20, 0xbf, 0x60, 0xd8, 0xe3, 0x06, 0xf7,
	0xa7, 0x3a, 0x5e, 0x45, 0x57, 0x7d, 0x9f, 0x81, 0x07, 0x89, 0xf1, 0x52, 0xd0, 0x2e, 0xe4, 0x98,
	0x40, 0x44, 0xec, 0xd2, 0xce, 0x8b, 0x64, 0x2d, 0x3f, 0x90, 0xa2, 0x2e, 0x4d, 0x99, 0x27, 0xd8,
	0x37, 0xfc, 0x5d, 0x48, 0x47, 0x2a, 0xc4, 0xdf, 0x09, 0xe5, 0x56, 0x60, 0x01, 0x3d, 0xcf, 0xf1,
	0x84, 0x38, 0x05, 0x2d, 0x34, 0x54, 0x0f, 0x72, 0x61, 0x02, 0xb2, 0x0a, 0xa4, 0x77, 0xbc, 0x7b,
	0xdc, 0xef, 0xe9, 0xfd, 0x57, 0xbd, 0x6e, 0xbb, 0xd9, 0xd9, 0xef, 0xb4, 0x5b, 0xe5, 0x4f, 0xc8,
	0x32, 0x2c, 0x4a, 0xfc, 0xa8, 0xdf, 0xee, 0xb7, 0x5b, 0x65, 0x85, 0xac, 0x40, 0x59, 0x42, 0xbd,
	0xfe, 0xde, 0x61, 0xe7, 0xf8, 0xb8, 0xdd, 0x2a, 0x67, 0x62, 0x68, 0xf3, 0xc7, 0x57, 0xfb, 0x1d,
	0xed, 0xb0, 0xdd, 0x2a, 0x67, 0x63, 0xe1, 0xfb, 0xbb, 0x9d, 0x97, 0xed, 0x56, 0xf9, 0xd6, 0xce,
	0x9f, 0x79, 0x28, 0xc6, 0xb6, 0x30, 0xf9, 0x19, 0xf2, 0xd1, 0x43, 0x81, 0x6c, 0xa4, 0x0a, 0x10,
	0x7f, 0x94, 0x54, 0xbf, 0xbc, 0xca, 0x4d, 0xea, 0x7b, 0x0e, 0xe5, 0xf9, 0x1b, 0x96, 0xd4, 0x92,
	0x63, 0x53, 0x6e, 0xe9, 0x6a, 0xfd, 0xba, 0xee, 0xb2, 0xe4, 0x19, 0x2c, 0xcd, 0xde, 0x2f, 0xe4,
	0xeb, 0xb4, 0xe7, 0x42, 0xc2, 0xed, 0x56, 0xfd, 0xe6, 0x7a, 0xce, 0xb2, 0x18, 0x42, 0x29, 0xde,
	0xd1, 0xc9, 0xe3, 0xe4, 0xe8, 0x84, 0xcb, 0xa5, 0xfa, 0xd5, 0x75, 0x5c, 0x65, 0x19, 0x0e, 0xcb,
	0x97, 0x7a, 0x32, 0x49, 0x11, 0x26, 0xed, 0xbe, 0xa8, 0x36, 0xae, 0xed, 0x2f, 0xab, 0xea, 0x00,
	0x17, 0xcd, 0x96, 0x6c, 0xa6, 0x2e, 0xf9, 0x5c, 0x9d, 0xad, 0xab, 0x1d, 0x65, 0x81, 0xdf, 0xa1,
	0x14, 0xef, 0x9f, 0xe4, 0x59, 0x8a, 0xf6, 0x1f, 0xec, 0xe0, 0xd5, 0xe7, 0x37, 0x8c, 0x92, 0xc5,
	0xff, 0x50, 0x60, 0x35, 0xb9, 0xdd, 0x92, 0xa7, 0xe9, 0x5b, 0x2e, 0xb5, 0xa7, 0x57, 0x9f, 0xdd,
	0x2c, 0x48, 0xb2, 0xf8, 0x0d, 0xee, 0x26, 0x34, 0x17, 0xf2, 0xe4, 0x06, 0x7d, 0x28, 0x2c, 0xbf,
	0x7d, 0xe3, 0xce, 0xb5, 0xc7, 0x7e, 0x39, 0x7f, 0x43, 0xf9, 0xa9, 0x3f, 0xa8, 0x9b, 0xce, 0xa8,
	0xd1, 0x1c, 0x3a, 0xbe, 0x55, 0xeb, 0x75, 0xdb, 0x8d, 0x28, 0x51, 0x6d, 0xe4, 0x58, 0xfe, 0x10,
	0x59, 0xcd, 0xf5, 0x9c, 0x5f, 0xd1, 0xe4, 0x0d, 0xee, 0x19, 0x36, 0x33, 0x1d, 0x0b, 0x6b, 0xc1,
	0x5d, 0x88, 0x5e, 0xcd, 0x76, 0x2c, 0x6c, 0x88, 0xe7, 0x70, 0xc3, 0x1c, 0x52, 0xf1, 0x43, 0x93,
	0xf4, 0x8b, 0xf3, 0x6d, 0xf4, 0x3d, 0xde, 0x1e, 0xe4, 0x84, 0xfb, 0xd3, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x67, 0x9d, 0xaf, 0x69, 0x4b, 0x0d, 0x00, 0x00,
}
