// Livepeer Payments v1 — PayerDaemon service.
//
// The PayerDaemon runs next to a payer application (a specialized PayerApp —
// e.g., an OpenAI bridge or a Livepeer gateway). It creates and signs tickets,
// manages per-session sender nonces, and watches the payer's on-chain escrow.
//
// This service is mounted only when the daemon is started with
// `--mode=sender`. Calls to it in receiver mode return UNIMPLEMENTED.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: livepeer/payments/v1/payer_daemon.proto

package paymentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayerDaemon_CreatePayment_FullMethodName  = "/livepeer.payments.v1.PayerDaemon/CreatePayment"
	PayerDaemon_GetDepositInfo_FullMethodName = "/livepeer.payments.v1.PayerDaemon/GetDepositInfo"
)

// PayerDaemonClient is the client API for PayerDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayerDaemonClient interface {
	// Create a payment blob (a `Payment` carrying one ticket) for a selected
	// payee identity at an exact face value. The daemon resolves the payee's
	// worker URL via the local resolver, fetches canonical TicketParams from
	// the payee-side ticket-params endpoint, then signs a wire-format Payment.
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	// Inspect the payer's current TicketBroker deposit/reserve state. Read-only;
	// the daemon does not fund escrow.
	GetDepositInfo(ctx context.Context, in *GetDepositInfoRequest, opts ...grpc.CallOption) (*GetDepositInfoResponse, error)
}

type payerDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewPayerDaemonClient(cc grpc.ClientConnInterface) PayerDaemonClient {
	return &payerDaemonClient{cc}
}

func (c *payerDaemonClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payerDaemonClient) GetDepositInfo(ctx context.Context, in *GetDepositInfoRequest, opts ...grpc.CallOption) (*GetDepositInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositInfoResponse)
	err := c.cc.Invoke(ctx, PayerDaemon_GetDepositInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayerDaemonServer is the server API for PayerDaemon service.
// All implementations should embed UnimplementedPayerDaemonServer
// for forward compatibility.
type PayerDaemonServer interface {
	// Create a payment blob (a `Payment` carrying one ticket) for a selected
	// payee identity at an exact face value. The daemon resolves the payee's
	// worker URL via the local resolver, fetches canonical TicketParams from
	// the payee-side ticket-params endpoint, then signs a wire-format Payment.
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	// Inspect the payer's current TicketBroker deposit/reserve state. Read-only;
	// the daemon does not fund escrow.
	GetDepositInfo(context.Context, *GetDepositInfoRequest) (*GetDepositInfoResponse, error)
}

// UnimplementedPayerDaemonServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayerDaemonServer struct{}

func (UnimplementedPayerDaemonServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPayerDaemonServer) GetDepositInfo(context.Context, *GetDepositInfoRequest) (*GetDepositInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDepositInfo not implemented")
}
func (UnimplementedPayerDaemonServer) testEmbeddedByValue() {}

// UnsafePayerDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayerDaemonServer will
// result in compilation errors.
type UnsafePayerDaemonServer interface {
	mustEmbedUnimplementedPayerDaemonServer()
}

func RegisterPayerDaemonServer(s grpc.ServiceRegistrar, srv PayerDaemonServer) {
	// If the following call panics, it indicates UnimplementedPayerDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayerDaemon_ServiceDesc, srv)
}

func _PayerDaemon_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayerDaemon_GetDepositInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayerDaemonServer).GetDepositInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayerDaemon_GetDepositInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayerDaemonServer).GetDepositInfo(ctx, req.(*GetDepositInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayerDaemon_ServiceDesc is the grpc.ServiceDesc for PayerDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayerDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livepeer.payments.v1.PayerDaemon",
	HandlerType: (*PayerDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PayerDaemon_CreatePayment_Handler,
		},
		{
			MethodName: "GetDepositInfo",
			Handler:    _PayerDaemon_GetDepositInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livepeer/payments/v1/payer_daemon.proto",
}
