// Livepeer Payments v1 — PayerDaemon service.
//
// The PayerDaemon runs next to a payer application (a specialized PayerApp —
// e.g., an OpenAI bridge or a Livepeer gateway). It creates and signs tickets,
// manages per-session sender nonces, and watches the payer's on-chain escrow.
//
// This service is mounted only when the daemon is started with
// `--mode=sender`. Calls to it in receiver mode return UNIMPLEMENTED.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: livepeer/payments/v1/payer_daemon.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact face value to mint into the ticket, in wei, big-endian bytes.
	FaceValue []byte `protobuf:"bytes,1,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Recipient orchestrator identity (the on-chain payee address), 20 raw
	// bytes. The daemon resolves a worker URL for this address via the local
	// service-registry-daemon resolver.
	Recipient []byte `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Capability being purchased, e.g. "openai:/v1/chat/completions". Sender
	// mode forwards this to the payee-side ticket-params endpoint so the worker
	// can validate the request against its offered routes.
	Capability string `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	// Offering within the capability being purchased, e.g. a model identifier.
	// Sender mode forwards this to the payee-side ticket-params endpoint.
	Offering      string `protobuf:"bytes,4,opt,name=offering,proto3" json:"offering,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_livepeer_payments_v1_payer_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payer_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payer_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetFaceValue() []byte {
	if x != nil {
		return x.FaceValue
	}
	return nil
}

func (x *CreatePaymentRequest) GetRecipient() []byte {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *CreatePaymentRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CreatePaymentRequest) GetOffering() string {
	if x != nil {
		return x.Offering
	}
	return ""
}

type CreatePaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wire-format `livepeer.payments.v1.Payment` bytes. The caller attaches
	// these to its app-level request to the payee (typically as an HTTP header).
	PaymentBytes []byte `protobuf:"bytes,1,opt,name=payment_bytes,json=paymentBytes,proto3" json:"payment_bytes,omitempty"`
	// Number of tickets this payment carries (for metrics / audit).
	TicketsCreated int32 `protobuf:"varint,2,opt,name=tickets_created,json=ticketsCreated,proto3" json:"tickets_created,omitempty"`
	// Aggregate expected value (EV = face_value × win_prob) committed by this
	// payment, in wei, big-endian bytes.
	ExpectedValue []byte `protobuf:"bytes,3,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_livepeer_payments_v1_payer_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payer_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payer_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetPaymentBytes() []byte {
	if x != nil {
		return x.PaymentBytes
	}
	return nil
}

func (x *CreatePaymentResponse) GetTicketsCreated() int32 {
	if x != nil {
		return x.TicketsCreated
	}
	return 0
}

func (x *CreatePaymentResponse) GetExpectedValue() []byte {
	if x != nil {
		return x.ExpectedValue
	}
	return nil
}

type GetDepositInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositInfoRequest) Reset() {
	*x = GetDepositInfoRequest{}
	mi := &file_livepeer_payments_v1_payer_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositInfoRequest) ProtoMessage() {}

func (x *GetDepositInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payer_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDepositInfoRequest) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payer_daemon_proto_rawDescGZIP(), []int{2}
}

type GetDepositInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current on-chain deposit (wei, big-endian bytes).
	Deposit []byte `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	// Current on-chain reserve (wei, big-endian bytes).
	Reserve []byte `protobuf:"bytes,2,opt,name=reserve,proto3" json:"reserve,omitempty"`
	// If the payer has initiated an unlock, the round at which withdrawal
	// becomes possible. Zero when no unlock is pending.
	WithdrawRound int64 `protobuf:"varint,3,opt,name=withdraw_round,json=withdrawRound,proto3" json:"withdraw_round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositInfoResponse) Reset() {
	*x = GetDepositInfoResponse{}
	mi := &file_livepeer_payments_v1_payer_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositInfoResponse) ProtoMessage() {}

func (x *GetDepositInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livepeer_payments_v1_payer_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDepositInfoResponse) Descriptor() ([]byte, []int) {
	return file_livepeer_payments_v1_payer_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetDepositInfoResponse) GetDeposit() []byte {
	if x != nil {
		return x.Deposit
	}
	return nil
}

func (x *GetDepositInfoResponse) GetReserve() []byte {
	if x != nil {
		return x.Reserve
	}
	return nil
}

func (x *GetDepositInfoResponse) GetWithdrawRound() int64 {
	if x != nil {
		return x.WithdrawRound
	}
	return 0
}

var File_livepeer_payments_v1_payer_daemon_proto protoreflect.FileDescriptor

const file_livepeer_payments_v1_payer_daemon_proto_rawDesc = "" +
	"\n" +
	"'livepeer/payments/v1/payer_daemon.proto\x12\x14livepeer.payments.v1\"\x8f\x01\n" +
	"\x14CreatePaymentRequest\x12\x1d\n" +
	"\n" +
	"face_value\x18\x01 \x01(\fR\tfaceValue\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\fR\trecipient\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\tR\n" +
	"capability\x12\x1a\n" +
	"\boffering\x18\x04 \x01(\tR\boffering\"\x8c\x01\n" +
	"\x15CreatePaymentResponse\x12#\n" +
	"\rpayment_bytes\x18\x01 \x01(\fR\fpaymentBytes\x12'\n" +
	"\x0ftickets_created\x18\x02 \x01(\x05R\x0eticketsCreated\x12%\n" +
	"\x0eexpected_value\x18\x03 \x01(\fR\rexpectedValue\"\x17\n" +
	"\x15GetDepositInfoRequest\"s\n" +
	"\x16GetDepositInfoResponse\x12\x18\n" +
	"\adeposit\x18\x01 \x01(\fR\adeposit\x12\x18\n" +
	"\areserve\x18\x02 \x01(\fR\areserve\x12%\n" +
	"\x0ewithdraw_round\x18\x03 \x01(\x03R\rwithdrawRound2\xe4\x01\n" +
	"\vPayerDaemon\x12h\n" +
	"\rCreatePayment\x12*.livepeer.payments.v1.CreatePaymentRequest\x1a+.livepeer.payments.v1.CreatePaymentResponse\x12k\n" +
	"\x0eGetDepositInfo\x12+.livepeer.payments.v1.GetDepositInfoRequest\x1a,.livepeer.payments.v1.GetDepositInfoResponseB\x89\x02\n" +
	"\x18com.livepeer.payments.v1B\x10PayerDaemonProtoP\x01Zigithub.com/Cloud-SPE/livepeer-modules-project/payment-daemon/proto/gen/go/livepeer/payments/v1;paymentsv1\xa2\x02\x03LPX\xaa\x02\x14Livepeer.Payments.V1\xca\x02\x14Livepeer\\Payments\\V1\xe2\x02 Livepeer\\Payments\\V1\\GPBMetadata\xea\x02\x16Livepeer::Payments::V1b\x06proto3"

var (
	file_livepeer_payments_v1_payer_daemon_proto_rawDescOnce sync.Once
	file_livepeer_payments_v1_payer_daemon_proto_rawDescData []byte
)

func file_livepeer_payments_v1_payer_daemon_proto_rawDescGZIP() []byte {
	file_livepeer_payments_v1_payer_daemon_proto_rawDescOnce.Do(func() {
		file_livepeer_payments_v1_payer_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_payer_daemon_proto_rawDesc), len(file_livepeer_payments_v1_payer_daemon_proto_rawDesc)))
	})
	return file_livepeer_payments_v1_payer_daemon_proto_rawDescData
}

var file_livepeer_payments_v1_payer_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_livepeer_payments_v1_payer_daemon_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),   // 0: livepeer.payments.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),  // 1: livepeer.payments.v1.CreatePaymentResponse
	(*GetDepositInfoRequest)(nil),  // 2: livepeer.payments.v1.GetDepositInfoRequest
	(*GetDepositInfoResponse)(nil), // 3: livepeer.payments.v1.GetDepositInfoResponse
}
var file_livepeer_payments_v1_payer_daemon_proto_depIdxs = []int32{
	0, // 0: livepeer.payments.v1.PayerDaemon.CreatePayment:input_type -> livepeer.payments.v1.CreatePaymentRequest
	2, // 1: livepeer.payments.v1.PayerDaemon.GetDepositInfo:input_type -> livepeer.payments.v1.GetDepositInfoRequest
	1, // 2: livepeer.payments.v1.PayerDaemon.CreatePayment:output_type -> livepeer.payments.v1.CreatePaymentResponse
	3, // 3: livepeer.payments.v1.PayerDaemon.GetDepositInfo:output_type -> livepeer.payments.v1.GetDepositInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_livepeer_payments_v1_payer_daemon_proto_init() }
func file_livepeer_payments_v1_payer_daemon_proto_init() {
	if File_livepeer_payments_v1_payer_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livepeer_payments_v1_payer_daemon_proto_rawDesc), len(file_livepeer_payments_v1_payer_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livepeer_payments_v1_payer_daemon_proto_goTypes,
		DependencyIndexes: file_livepeer_payments_v1_payer_daemon_proto_depIdxs,
		MessageInfos:      file_livepeer_payments_v1_payer_daemon_proto_msgTypes,
	}.Build()
	File_livepeer_payments_v1_payer_daemon_proto = out.File
	file_livepeer_payments_v1_payer_daemon_proto_goTypes = nil
	file_livepeer_payments_v1_payer_daemon_proto_depIdxs = nil
}
