// Code generated by protoc-gen-go. DO NOT EDIT.
// source: livepeer/payments/v1/payer_daemon.proto

package paymentsv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartSessionRequest struct {
	// Ticket parameters as returned by the payee's `GetQuote`.
	TicketParams *TicketParams `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// Optional caller-chosen label used only in the daemon's audit log.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Price the payee committed to when issuing `ticket_params`. The daemon
	// stores this price on the session and:
	//  1. Embeds it in every Payment as `expected_price` so the payee's
	//     `recipientRand` HMAC inputs match what they used at quote time.
	//     Without it, the payee re-derives `recipientRand` against price=0
	//     and the recipient_rand_hash check fails — see receiver.go's
	//     `computeRecipientRand`.
	//  2. Sizes ticket batches against `work_units × price`.
	//
	// REQUIRED for any session that will produce non-free tickets. Free /
	// bootstrap sessions may pass `{ price_per_unit_wei: "0", pixels_per_unit: "1" }`.
	PriceInfo            *PriceInfo `protobuf:"bytes,3,opt,name=price_info,json=priceInfo,proto3" json:"price_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StartSessionRequest) Reset()         { *m = StartSessionRequest{} }
func (m *StartSessionRequest) String() string { return proto.CompactTextString(m) }
func (*StartSessionRequest) ProtoMessage()    {}
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9521c073917524bb, []int{0}
}

func (m *StartSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSessionRequest.Unmarshal(m, b)
}
func (m *StartSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSessionRequest.Marshal(b, m, deterministic)
}
func (m *StartSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSessionRequest.Merge(m, src)
}
func (m *StartSessionRequest) XXX_Size() int {
	return xxx_messageInfo_StartSessionRequest.Size(m)
}
func (m *StartSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartSessionRequest proto.InternalMessageInfo

func (m *StartSessionRequest) GetTicketParams() *TicketParams {
	if m != nil {
		return m.TicketParams
	}
	return nil
}

func (m *StartSessionRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *StartSessionRequest) GetPriceInfo() *PriceInfo {
	if m != nil {
		return m.PriceInfo
	}
	return nil
}

type StartSessionResponse struct {
	// Opaque session identifier. Include in subsequent `CreatePayment` /
	// `CloseSession` calls for this relationship.
	WorkId               string   `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSessionResponse) Reset()         { *m = StartSessionResponse{} }
func (m *StartSessionResponse) String() string { return proto.CompactTextString(m) }
func (*StartSessionResponse) ProtoMessage()    {}
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9521c073917524bb, []int{1}
}

func (m *StartSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSessionResponse.Unmarshal(m, b)
}
func (m *StartSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSessionResponse.Marshal(b, m, deterministic)
}
func (m *StartSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSessionResponse.Merge(m, src)
}
func (m *StartSessionResponse) XXX_Size() int {
	return xxx_messageInfo_StartSessionResponse.Size(m)
}
func (m *StartSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartSessionResponse proto.InternalMessageInfo

func (m *StartSessionResponse) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

type CreatePaymentRequest struct {
	// Session previously returned by `StartSession`.
	WorkId string `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	// Number of work units the payment should cover. The daemon consults the
	// session's PriceInfo and produces tickets whose cumulative expected value
	// >= `work_units × price`.
	WorkUnits            int64    `protobuf:"varint,2,opt,name=work_units,json=workUnits,proto3" json:"work_units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentRequest) Reset()         { *m = CreatePaymentRequest{} }
func (m *CreatePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentRequest) ProtoMessage()    {}
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9521c073917524bb, []int{2}
}

func (m *CreatePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentRequest.Unmarshal(m, b)
}
func (m *CreatePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentRequest.Merge(m, src)
}
func (m *CreatePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentRequest.Size(m)
}
func (m *CreatePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentRequest proto.InternalMessageInfo

func (m *CreatePaymentRequest) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

func (m *CreatePaymentRequest) GetWorkUnits() int64 {
	if m != nil {
		return m.WorkUnits
	}
	return 0
}

type CreatePaymentResponse struct {
	// Wire-format `livepeer.payments.v1.Payment` bytes. The caller attaches
	// these to its app-level request to the payee (typically as an HTTP header).
	PaymentBytes []byte `protobuf:"bytes,1,opt,name=payment_bytes,json=paymentBytes,proto3" json:"payment_bytes,omitempty"`
	// Number of tickets this payment carries (for metrics / audit).
	TicketsCreated int32 `protobuf:"varint,2,opt,name=tickets_created,json=ticketsCreated,proto3" json:"tickets_created,omitempty"`
	// Aggregate expected value (EV = face_value × win_prob) committed by this
	// payment, in wei, big-endian bytes.
	ExpectedValue        []byte   `protobuf:"bytes,3,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentResponse) Reset()         { *m = CreatePaymentResponse{} }
func (m *CreatePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentResponse) ProtoMessage()    {}
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9521c073917524bb, []int{3}
}

func (m *CreatePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentResponse.Unmarshal(m, b)
}
func (m *CreatePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentResponse.Marshal(b, m, deterministic)
}
func (m *CreatePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentResponse.Merge(m, src)
}
func (m *CreatePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentResponse.Size(m)
}
func (m *CreatePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentResponse proto.InternalMessageInfo

func (m *CreatePaymentResponse) GetPaymentBytes() []byte {
	if m != nil {
		return m.PaymentBytes
	}
	return nil
}

func (m *CreatePaymentResponse) GetTicketsCreated() int32 {
	if m != nil {
		return m.TicketsCreated
	}
	return 0
}

func (m *CreatePaymentResponse) GetExpectedValue() []byte {
	if m != nil {
		return m.ExpectedValue
	}
	return nil
}

type PayerDaemonCloseSessionRequest struct {
	WorkId               string   `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayerDaemonCloseSessionRequest) Reset()         { *m = PayerDaemonCloseSessionRequest{} }
func (m *PayerDaemonCloseSessionRequest) String() string { return proto.CompactTextString(m) }
func (*PayerDaemonCloseSessionRequest) ProtoMessage()    {}
func (*PayerDaemonCloseSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9521c073917524bb, []int{4}
}

func (m *PayerDaemonCloseSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayerDaemonCloseSessionRequest.Unmarshal(m, b)
}
func (m *PayerDaemonCloseSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayerDaemonCloseSessionRequest.Marshal(b, m, deterministic)
}
func (m *PayerDaemonCloseSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayerDaemonCloseSessionRequest.Merge(m, src)
}
func (m *PayerDaemonCloseSessionRequest) XXX_Size() int {
	return xxx_messageInfo_PayerDaemonCloseSessionRequest.Size(m)
}
func (m *PayerDaemonCloseSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayerDaemonCloseSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayerDaemonCloseSessionRequest proto.InternalMessageInfo

func (m *PayerDaemonCloseSessionRequest) GetWorkId() string {
	if m != nil {
		return m.WorkId
	}
	return ""
}

type PayerDaemonCloseSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayerDaemonCloseSessionResponse) Reset()         { *m = PayerDaemonCloseSessionResponse{} }
func (m *PayerDaemonCloseSessionResponse) String() string { return proto.CompactTextString(m) }
func (*PayerDaemonCloseSessionResponse) ProtoMessage()    {}
func (*PayerDaemonCloseSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9521c073917524bb, []int{5}
}

func (m *PayerDaemonCloseSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayerDaemonCloseSessionResponse.Unmarshal(m, b)
}
func (m *PayerDaemonCloseSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayerDaemonCloseSessionResponse.Marshal(b, m, deterministic)
}
func (m *PayerDaemonCloseSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayerDaemonCloseSessionResponse.Merge(m, src)
}
func (m *PayerDaemonCloseSessionResponse) XXX_Size() int {
	return xxx_messageInfo_PayerDaemonCloseSessionResponse.Size(m)
}
func (m *PayerDaemonCloseSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayerDaemonCloseSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayerDaemonCloseSessionResponse proto.InternalMessageInfo

type GetDepositInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDepositInfoRequest) Reset()         { *m = GetDepositInfoRequest{} }
func (m *GetDepositInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetDepositInfoRequest) ProtoMessage()    {}
func (*GetDepositInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9521c073917524bb, []int{6}
}

func (m *GetDepositInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDepositInfoRequest.Unmarshal(m, b)
}
func (m *GetDepositInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDepositInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetDepositInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDepositInfoRequest.Merge(m, src)
}
func (m *GetDepositInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetDepositInfoRequest.Size(m)
}
func (m *GetDepositInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDepositInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDepositInfoRequest proto.InternalMessageInfo

type GetDepositInfoResponse struct {
	// Current on-chain deposit (wei, big-endian bytes).
	Deposit []byte `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	// Current on-chain reserve (wei, big-endian bytes).
	Reserve []byte `protobuf:"bytes,2,opt,name=reserve,proto3" json:"reserve,omitempty"`
	// If the payer has initiated an unlock, the round at which withdrawal
	// becomes possible. Zero when no unlock is pending.
	WithdrawRound        int64    `protobuf:"varint,3,opt,name=withdraw_round,json=withdrawRound,proto3" json:"withdraw_round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDepositInfoResponse) Reset()         { *m = GetDepositInfoResponse{} }
func (m *GetDepositInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetDepositInfoResponse) ProtoMessage()    {}
func (*GetDepositInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9521c073917524bb, []int{7}
}

func (m *GetDepositInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDepositInfoResponse.Unmarshal(m, b)
}
func (m *GetDepositInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDepositInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetDepositInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDepositInfoResponse.Merge(m, src)
}
func (m *GetDepositInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetDepositInfoResponse.Size(m)
}
func (m *GetDepositInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDepositInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDepositInfoResponse proto.InternalMessageInfo

func (m *GetDepositInfoResponse) GetDeposit() []byte {
	if m != nil {
		return m.Deposit
	}
	return nil
}

func (m *GetDepositInfoResponse) GetReserve() []byte {
	if m != nil {
		return m.Reserve
	}
	return nil
}

func (m *GetDepositInfoResponse) GetWithdrawRound() int64 {
	if m != nil {
		return m.WithdrawRound
	}
	return 0
}

func init() {
	proto.RegisterType((*StartSessionRequest)(nil), "livepeer.payments.v1.StartSessionRequest")
	proto.RegisterType((*StartSessionResponse)(nil), "livepeer.payments.v1.StartSessionResponse")
	proto.RegisterType((*CreatePaymentRequest)(nil), "livepeer.payments.v1.CreatePaymentRequest")
	proto.RegisterType((*CreatePaymentResponse)(nil), "livepeer.payments.v1.CreatePaymentResponse")
	proto.RegisterType((*PayerDaemonCloseSessionRequest)(nil), "livepeer.payments.v1.PayerDaemonCloseSessionRequest")
	proto.RegisterType((*PayerDaemonCloseSessionResponse)(nil), "livepeer.payments.v1.PayerDaemonCloseSessionResponse")
	proto.RegisterType((*GetDepositInfoRequest)(nil), "livepeer.payments.v1.GetDepositInfoRequest")
	proto.RegisterType((*GetDepositInfoResponse)(nil), "livepeer.payments.v1.GetDepositInfoResponse")
}

func init() {
	proto.RegisterFile("livepeer/payments/v1/payer_daemon.proto", fileDescriptor_9521c073917524bb)
}

var fileDescriptor_9521c073917524bb = []byte{
	// 574 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0x56, 0x7f, 0xd5, 0x36, 0xf5, 0x2c, 0xdd, 0x4f, 0x32, 0x1d, 0xab, 0x2a, 0xc1, 0x4a, 0x10,
	0xda, 0xf8, 0xd3, 0x44, 0x1d, 0x70, 0x81, 0x90, 0xb8, 0x58, 0x87, 0xa6, 0xdd, 0xa0, 0xca, 0x05,
	0x2e, 0xb8, 0x89, 0xd2, 0xf8, 0x8c, 0x86, 0xa6, 0x71, 0x66, 0x3b, 0x29, 0x15, 0xaf, 0xc0, 0xe3,
	0xf0, 0x10, 0x3c, 0x16, 0xb2, 0x93, 0x48, 0x6d, 0x95, 0xa0, 0x72, 0xe7, 0xf3, 0xf9, 0x3b, 0xff,
	0x3f, 0x1b, 0xce, 0xa2, 0x30, 0xc3, 0x04, 0x51, 0xb8, 0x89, 0xbf, 0x5a, 0x60, 0xac, 0xa4, 0x9b,
	0x0d, 0xf5, 0x19, 0x85, 0xc7, 0x7c, 0x5c, 0xf0, 0xd8, 0x49, 0x04, 0x57, 0x9c, 0x74, 0x4a, 0xa2,
	0x53, 0x12, 0x9d, 0x6c, 0xd8, 0xeb, 0x57, 0xba, 0xab, 0x55, 0x82, 0x32, 0xf7, 0xb3, 0x7f, 0x35,
	0xe0, 0xde, 0x44, 0xf9, 0x42, 0x4d, 0x50, 0xca, 0x90, 0xc7, 0x14, 0xef, 0x52, 0x94, 0x8a, 0x5c,
	0x43, 0x5b, 0x85, 0xc1, 0x1c, 0x95, 0x97, 0xf8, 0xc2, 0x5f, 0xc8, 0x6e, 0xa3, 0xdf, 0x38, 0x3f,
	0xbc, 0xb0, 0x9d, 0xaa, 0x3c, 0xce, 0x47, 0x43, 0x1d, 0x1b, 0x26, 0xb5, 0xd4, 0x9a, 0x45, 0x3a,
	0xb0, 0x17, 0xf9, 0x53, 0x8c, 0xba, 0xff, 0xf5, 0x1b, 0xe7, 0x2d, 0x9a, 0x1b, 0xe4, 0x1d, 0x40,
	0x22, 0xc2, 0x00, 0xbd, 0x30, 0xbe, 0xe5, 0xdd, 0xa6, 0x89, 0x7d, 0x5a, 0x1d, 0x7b, 0xac, 0x79,
	0x37, 0xf1, 0x2d, 0xa7, 0xad, 0xa4, 0x3c, 0xda, 0x2e, 0x74, 0x36, 0xab, 0x96, 0x09, 0x8f, 0x25,
	0x92, 0x13, 0x38, 0x58, 0x72, 0x31, 0xf7, 0x42, 0x66, 0x0a, 0x6e, 0xd1, 0x7d, 0x6d, 0xde, 0x30,
	0xfb, 0x03, 0x74, 0x46, 0x02, 0x7d, 0x85, 0xe3, 0x3c, 0x74, 0xd9, 0x67, 0x9d, 0x03, 0x79, 0x00,
	0x60, 0x2e, 0xd2, 0x38, 0x54, 0xd2, 0x14, 0xdf, 0xa4, 0x2d, 0x8d, 0x7c, 0xd2, 0x80, 0xfd, 0xb3,
	0x01, 0xc7, 0x5b, 0x01, 0x8b, 0x12, 0x1e, 0x43, 0xbb, 0x28, 0xdf, 0x9b, 0xae, 0x14, 0xe6, 0x93,
	0xb3, 0xa8, 0x55, 0x80, 0x97, 0x1a, 0x23, 0x67, 0xf0, 0x7f, 0x3e, 0x25, 0xe9, 0x05, 0x26, 0x0a,
	0x33, 0x29, 0xf6, 0xe8, 0x51, 0x01, 0xe7, 0xb1, 0x19, 0x79, 0x02, 0x47, 0xf8, 0x3d, 0xc1, 0x40,
	0x21, 0xf3, 0x32, 0x3f, 0x4a, 0xd1, 0x0c, 0xcb, 0xa2, 0xed, 0x12, 0xfd, 0xac, 0x41, 0xfb, 0x0d,
	0x3c, 0x1c, 0x6b, 0x51, 0x5c, 0x19, 0x4d, 0x8c, 0x22, 0x2e, 0x71, 0x6b, 0xa1, 0xb5, 0x93, 0x79,
	0x04, 0xa7, 0xb5, 0xae, 0x79, 0x4b, 0xf6, 0x09, 0x1c, 0x5f, 0xa3, 0xba, 0xc2, 0x84, 0xcb, 0x50,
	0x99, 0x55, 0xe4, 0x41, 0x6d, 0x09, 0xf7, 0xb7, 0x2f, 0x8a, 0x29, 0x74, 0xe1, 0x80, 0xe5, 0x70,
	0xd1, 0x7f, 0x69, 0xea, 0x1b, 0x81, 0x12, 0x45, 0x86, 0xa6, 0x65, 0x8b, 0x96, 0xa6, 0xee, 0x75,
	0x19, 0xaa, 0x19, 0x13, 0xfe, 0xd2, 0x13, 0x3c, 0x8d, 0x99, 0xe9, 0xb5, 0x49, 0xdb, 0x25, 0x4a,
	0x35, 0x78, 0xf1, 0xbb, 0x09, 0x87, 0x6b, 0x15, 0x13, 0x04, 0x6b, 0x5d, 0x0b, 0xe4, 0x69, 0xb5,
	0x8e, 0x2a, 0x54, 0xde, 0x7b, 0xb6, 0x0b, 0xb5, 0xe8, 0x68, 0x06, 0xed, 0x8d, 0x85, 0x93, 0x1a,
	0xe7, 0x2a, 0x99, 0xf5, 0x9e, 0xef, 0xc4, 0x2d, 0x32, 0xfd, 0x00, 0x6b, 0x7d, 0x0d, 0xe4, 0x55,
	0xcd, 0xc3, 0xf8, 0xeb, 0xc2, 0x7b, 0xaf, 0xff, 0xd1, 0xab, 0x48, 0x3e, 0x87, 0xa3, 0xcd, 0x95,
	0x92, 0x9a, 0xda, 0x2b, 0x15, 0xd1, 0x7b, 0xb1, 0x1b, 0x39, 0x4f, 0x76, 0x29, 0xbf, 0xdc, 0x7d,
	0x0d, 0xd5, 0x2c, 0x9d, 0x3a, 0x01, 0x5f, 0xb8, 0xa3, 0x88, 0xa7, 0x6c, 0x30, 0x19, 0xbf, 0x77,
	0xcb, 0x18, 0x83, 0x05, 0x67, 0x69, 0x84, 0x72, 0x90, 0x08, 0xfe, 0x0d, 0x03, 0xe5, 0x2a, 0xe1,
	0xc7, 0x32, 0xe0, 0x0c, 0x07, 0x5a, 0xbd, 0x28, 0x06, 0x31, 0x67, 0xe8, 0x9a, 0xaf, 0xcc, 0x0d,
	0xa2, 0xd0, 0xfc, 0x70, 0x55, 0x7f, 0xde, 0xdb, 0xf2, 0x9c, 0x0d, 0xa7, 0xfb, 0x86, 0xfe, 0xf2,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0x97, 0x0f, 0xe1, 0x5c, 0x05, 0x00, 0x00,
}
