// Code generated by protoc-gen-go. DO NOT EDIT.
// source: livepeer/payments/v1/types.proto

package paymentsv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PriceInfo conveys pricing info for a unit of work.
//
// `pixelsPerUnit` is a historical name; the denominator is really just "work
// units" — pixels, tokens, seconds, or anything the consumer chooses. For wire
// compatibility the field name is preserved.
type PriceInfo struct {
	// Price in wei per `pixels_per_unit` units of work.
	//
	// NOTE ON WIRE COMPAT: the proto field NAME differs from go-livepeer's
	// (`pricePerUnit` vs `price_per_unit`), but the field NUMBER is identical.
	// Proto encoding keys on the number, not the name, so bytes on the wire
	// remain compatible. The Go-generated field name is `PricePerUnit` in both
	// projects. See docs/design-docs/wire-compat.md.
	PricePerUnit int64 `protobuf:"varint,1,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	// Work units covered by `price_per_unit`. Setting `price_per_unit = 1` with
	// a larger `pixels_per_unit` lets pricing go finer than 1 wei per unit.
	PixelsPerUnit int64 `protobuf:"varint,2,opt,name=pixels_per_unit,json=pixelsPerUnit,proto3" json:"pixels_per_unit,omitempty"`
	// Capability this price applies to (uint32 capability ID, as in go-livepeer).
	// The daemon's RPC surface accepts string capability names and maps them to
	// this uint32 at the boundary.
	Capability uint32 `protobuf:"varint,3,opt,name=capability,proto3" json:"capability,omitempty"`
	// Non-binary constraint this price applies to (e.g., a specific model id).
	Constraint           string   `protobuf:"bytes,4,opt,name=constraint,proto3" json:"constraint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceInfo) Reset()         { *m = PriceInfo{} }
func (m *PriceInfo) String() string { return proto.CompactTextString(m) }
func (*PriceInfo) ProtoMessage()    {}
func (*PriceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c66b95c713a98, []int{0}
}

func (m *PriceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceInfo.Unmarshal(m, b)
}
func (m *PriceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceInfo.Marshal(b, m, deterministic)
}
func (m *PriceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceInfo.Merge(m, src)
}
func (m *PriceInfo) XXX_Size() int {
	return xxx_messageInfo_PriceInfo.Size(m)
}
func (m *PriceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PriceInfo proto.InternalMessageInfo

func (m *PriceInfo) GetPricePerUnit() int64 {
	if m != nil {
		return m.PricePerUnit
	}
	return 0
}

func (m *PriceInfo) GetPixelsPerUnit() int64 {
	if m != nil {
		return m.PixelsPerUnit
	}
	return 0
}

func (m *PriceInfo) GetCapability() uint32 {
	if m != nil {
		return m.Capability
	}
	return 0
}

func (m *PriceInfo) GetConstraint() string {
	if m != nil {
		return m.Constraint
	}
	return ""
}

// TicketParams is the recipient-controlled portion of a ticket. The payee
// issues these to a payer during discovery (via `GetQuote`); the payer uses
// them verbatim when constructing tickets in a `TicketBatch`.
type TicketParams struct {
	// ETH address of the recipient.
	Recipient []byte `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Payout in wei if the ticket wins. Represented as big-endian bytes.
	FaceValue []byte `protobuf:"bytes,2,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	// Probability the ticket wins, scaled to the 256-bit win-probability field
	// (maxWinProb = 2^256 - 1). Big-endian bytes.
	WinProb []byte `protobuf:"bytes,3,opt,name=win_prob,json=winProb,proto3" json:"win_prob,omitempty"`
	// 32-byte keccak-256 hash commitment to a random number held by the recipient.
	RecipientRandHash []byte `protobuf:"bytes,4,opt,name=recipient_rand_hash,json=recipientRandHash,proto3" json:"recipient_rand_hash,omitempty"`
	// Seed the recipient uses to derive the random number corresponding to
	// `recipient_rand_hash`.
	Seed []byte `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`
	// L1 block number after which this set of TicketParams is no longer valid.
	// Big-endian bytes.
	ExpirationBlock []byte `protobuf:"bytes,6,opt,name=expiration_block,json=expirationBlock,proto3" json:"expiration_block,omitempty"`
	// Expiration parameters used at ticket-validation time.
	ExpirationParams     *TicketExpirationParams `protobuf:"bytes,7,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TicketParams) Reset()         { *m = TicketParams{} }
func (m *TicketParams) String() string { return proto.CompactTextString(m) }
func (*TicketParams) ProtoMessage()    {}
func (*TicketParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c66b95c713a98, []int{1}
}

func (m *TicketParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketParams.Unmarshal(m, b)
}
func (m *TicketParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketParams.Marshal(b, m, deterministic)
}
func (m *TicketParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketParams.Merge(m, src)
}
func (m *TicketParams) XXX_Size() int {
	return xxx_messageInfo_TicketParams.Size(m)
}
func (m *TicketParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketParams proto.InternalMessageInfo

func (m *TicketParams) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *TicketParams) GetFaceValue() []byte {
	if m != nil {
		return m.FaceValue
	}
	return nil
}

func (m *TicketParams) GetWinProb() []byte {
	if m != nil {
		return m.WinProb
	}
	return nil
}

func (m *TicketParams) GetRecipientRandHash() []byte {
	if m != nil {
		return m.RecipientRandHash
	}
	return nil
}

func (m *TicketParams) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *TicketParams) GetExpirationBlock() []byte {
	if m != nil {
		return m.ExpirationBlock
	}
	return nil
}

func (m *TicketParams) GetExpirationParams() *TicketExpirationParams {
	if m != nil {
		return m.ExpirationParams
	}
	return nil
}

// TicketSenderParams contains per-ticket nonce + signature values that the
// sender produces while creating a ticket batch.
type TicketSenderParams struct {
	// Monotonically increasing counter that makes a ticket unique relative to a
	// given `recipient_rand_hash` in `TicketParams`.
	SenderNonce uint32 `protobuf:"varint,1,opt,name=sender_nonce,json=senderNonce,proto3" json:"sender_nonce,omitempty"`
	// Sender's ECDSA signature over the ticket hash.
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketSenderParams) Reset()         { *m = TicketSenderParams{} }
func (m *TicketSenderParams) String() string { return proto.CompactTextString(m) }
func (*TicketSenderParams) ProtoMessage()    {}
func (*TicketSenderParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c66b95c713a98, []int{2}
}

func (m *TicketSenderParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketSenderParams.Unmarshal(m, b)
}
func (m *TicketSenderParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketSenderParams.Marshal(b, m, deterministic)
}
func (m *TicketSenderParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketSenderParams.Merge(m, src)
}
func (m *TicketSenderParams) XXX_Size() int {
	return xxx_messageInfo_TicketSenderParams.Size(m)
}
func (m *TicketSenderParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketSenderParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketSenderParams proto.InternalMessageInfo

func (m *TicketSenderParams) GetSenderNonce() uint32 {
	if m != nil {
		return m.SenderNonce
	}
	return 0
}

func (m *TicketSenderParams) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// TicketExpirationParams carries the Livepeer "round" and associated block
// hash used to validate ticket freshness against the protocol round state.
type TicketExpirationParams struct {
	// Livepeer protocol round during which the tickets were created.
	CreationRound int64 `protobuf:"varint,1,opt,name=creation_round,json=creationRound,proto3" json:"creation_round,omitempty"`
	// Block hash associated with `creation_round`.
	CreationRoundBlockHash []byte   `protobuf:"bytes,2,opt,name=creation_round_block_hash,json=creationRoundBlockHash,proto3" json:"creation_round_block_hash,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *TicketExpirationParams) Reset()         { *m = TicketExpirationParams{} }
func (m *TicketExpirationParams) String() string { return proto.CompactTextString(m) }
func (*TicketExpirationParams) ProtoMessage()    {}
func (*TicketExpirationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c66b95c713a98, []int{3}
}

func (m *TicketExpirationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketExpirationParams.Unmarshal(m, b)
}
func (m *TicketExpirationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketExpirationParams.Marshal(b, m, deterministic)
}
func (m *TicketExpirationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketExpirationParams.Merge(m, src)
}
func (m *TicketExpirationParams) XXX_Size() int {
	return xxx_messageInfo_TicketExpirationParams.Size(m)
}
func (m *TicketExpirationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketExpirationParams.DiscardUnknown(m)
}

var xxx_messageInfo_TicketExpirationParams proto.InternalMessageInfo

func (m *TicketExpirationParams) GetCreationRound() int64 {
	if m != nil {
		return m.CreationRound
	}
	return 0
}

func (m *TicketExpirationParams) GetCreationRoundBlockHash() []byte {
	if m != nil {
		return m.CreationRoundBlockHash
	}
	return nil
}

// Payment is the on-the-wire payment message. One `Payment` can carry many
// tickets (one per entry in `ticket_sender_params`) so a payer can cover a
// whole segment / job / session in a single wire message.
type Payment struct {
	// Recipient-controlled ticket parameters. Stays the same across all tickets
	// in this payment.
	TicketParams *TicketParams `protobuf:"bytes,1,opt,name=ticket_params,json=ticketParams,proto3" json:"ticket_params,omitempty"`
	// ETH address of the sender.
	Sender []byte `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Shared expiration params for all tickets in this payment.
	ExpirationParams *TicketExpirationParams `protobuf:"bytes,3,opt,name=expiration_params,json=expirationParams,proto3" json:"expiration_params,omitempty"`
	// Per-ticket sender parameters (nonce + signature). One entry per ticket.
	TicketSenderParams []*TicketSenderParams `protobuf:"bytes,4,rep,name=ticket_sender_params,json=ticketSenderParams,proto3" json:"ticket_sender_params,omitempty"`
	// Payer's last-known price for this work. Used by the payee to detect stale
	// clients and trigger a re-quote.
	ExpectedPrice        *PriceInfo `protobuf:"bytes,5,opt,name=expected_price,json=expectedPrice,proto3" json:"expected_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d5c66b95c713a98, []int{4}
}

func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetTicketParams() *TicketParams {
	if m != nil {
		return m.TicketParams
	}
	return nil
}

func (m *Payment) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Payment) GetExpirationParams() *TicketExpirationParams {
	if m != nil {
		return m.ExpirationParams
	}
	return nil
}

func (m *Payment) GetTicketSenderParams() []*TicketSenderParams {
	if m != nil {
		return m.TicketSenderParams
	}
	return nil
}

func (m *Payment) GetExpectedPrice() *PriceInfo {
	if m != nil {
		return m.ExpectedPrice
	}
	return nil
}

func init() {
	proto.RegisterType((*PriceInfo)(nil), "livepeer.payments.v1.PriceInfo")
	proto.RegisterType((*TicketParams)(nil), "livepeer.payments.v1.TicketParams")
	proto.RegisterType((*TicketSenderParams)(nil), "livepeer.payments.v1.TicketSenderParams")
	proto.RegisterType((*TicketExpirationParams)(nil), "livepeer.payments.v1.TicketExpirationParams")
	proto.RegisterType((*Payment)(nil), "livepeer.payments.v1.Payment")
}

func init() {
	proto.RegisterFile("livepeer/payments/v1/types.proto", fileDescriptor_4d5c66b95c713a98)
}

var fileDescriptor_4d5c66b95c713a98 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0xb5, 0x4d, 0x69, 0xc9, 0x64, 0xd3, 0x0f, 0x53, 0x55, 0xa9, 0xc4, 0x47, 0x88, 0x00,
	0x05, 0x89, 0xec, 0xaa, 0xe5, 0x84, 0xb8, 0x15, 0x15, 0xe8, 0x05, 0x45, 0x2e, 0x20, 0xd1, 0xcb,
	0xca, 0xf1, 0x4e, 0x1b, 0xd3, 0x8d, 0x6d, 0x6c, 0x27, 0x6d, 0x79, 0x13, 0xde, 0x82, 0xd7, 0xe2,
	0x2d, 0xd0, 0xda, 0xbb, 0x69, 0x2a, 0xa2, 0x9e, 0xb8, 0xd9, 0x3f, 0xff, 0x3d, 0x33, 0xfe, 0x8f,
	0x6d, 0xe8, 0x16, 0x62, 0x86, 0x1a, 0xd1, 0xa4, 0x9a, 0x5d, 0x4f, 0x50, 0x3a, 0x9b, 0xce, 0xf6,
	0x53, 0x77, 0xad, 0xd1, 0x26, 0xda, 0x28, 0xa7, 0xc8, 0x4e, 0xad, 0x48, 0x6a, 0x45, 0x32, 0xdb,
	0xef, 0xfd, 0x8a, 0xa0, 0x39, 0x34, 0x82, 0xe3, 0xb1, 0x3c, 0x53, 0xe4, 0x19, 0x6c, 0xe8, 0x72,
	0x92, 0x69, 0x34, 0xd9, 0x54, 0x0a, 0xd7, 0x89, 0xba, 0x51, 0xbf, 0x41, 0x63, 0x4f, 0x87, 0x68,
	0xbe, 0x48, 0xe1, 0xc8, 0x0b, 0xd8, 0xd4, 0xe2, 0x0a, 0x0b, 0x7b, 0x23, 0x5b, 0xf1, 0xb2, 0x76,
	0xc0, 0xb5, 0xee, 0x31, 0x00, 0x67, 0x9a, 0x8d, 0x44, 0x21, 0xdc, 0x75, 0xa7, 0xd1, 0x8d, 0xfa,
	0x6d, 0xba, 0x40, 0xfc, 0xba, 0x92, 0xd6, 0x19, 0x26, 0xa4, 0xeb, 0xac, 0x76, 0xa3, 0x7e, 0x93,
	0x2e, 0x90, 0xde, 0xef, 0x15, 0x88, 0x3f, 0x0b, 0x7e, 0x81, 0x6e, 0xc8, 0x0c, 0x9b, 0x58, 0xf2,
	0x10, 0x9a, 0x06, 0xb9, 0xd0, 0x02, 0x65, 0xa8, 0x2c, 0xa6, 0x37, 0x80, 0x3c, 0x02, 0x38, 0x63,
	0x1c, 0xb3, 0x19, 0x2b, 0xa6, 0xe8, 0x2b, 0x8a, 0x69, 0xb3, 0x24, 0x5f, 0x4b, 0x40, 0xf6, 0xe0,
	0xfe, 0xa5, 0x90, 0x99, 0x36, 0x6a, 0xe4, 0x6b, 0x89, 0xe9, 0xfa, 0xa5, 0x90, 0x43, 0xa3, 0x46,
	0x24, 0x81, 0x07, 0xf3, 0x30, 0x99, 0x61, 0x32, 0xcf, 0xc6, 0xcc, 0x8e, 0x7d, 0x45, 0x31, 0xdd,
	0x9e, 0x2f, 0x51, 0x26, 0xf3, 0x8f, 0xcc, 0x8e, 0x09, 0x81, 0x55, 0x8b, 0x98, 0x77, 0xee, 0x79,
	0x81, 0x1f, 0x93, 0x97, 0xb0, 0x85, 0x57, 0x5a, 0x18, 0xe6, 0x84, 0x92, 0xd9, 0xa8, 0x50, 0xfc,
	0xa2, 0xb3, 0xe6, 0xd7, 0x37, 0x6f, 0xf8, 0x61, 0x89, 0xc9, 0x37, 0xd8, 0x5e, 0x90, 0x6a, 0x7f,
	0xb6, 0xce, 0x7a, 0x37, 0xea, 0xb7, 0x0e, 0x5e, 0x25, 0xcb, 0xba, 0x94, 0x04, 0x17, 0x8e, 0xe6,
	0x9b, 0x82, 0x1f, 0x74, 0x21, 0x63, 0x20, 0xbd, 0x63, 0x20, 0x41, 0x7b, 0x82, 0x32, 0x47, 0x53,
	0xf9, 0xf6, 0x14, 0x62, 0xeb, 0xe7, 0x99, 0x54, 0x92, 0xa3, 0xb7, 0xae, 0x4d, 0x5b, 0x81, 0x7d,
	0x2a, 0x11, 0xd9, 0x82, 0x86, 0x15, 0xe7, 0x95, 0x6b, 0xe5, 0xb0, 0xf7, 0x13, 0x76, 0x97, 0xa7,
	0x25, 0xcf, 0x61, 0x83, 0x1b, 0x0c, 0xd5, 0x1b, 0x35, 0x95, 0x79, 0x75, 0x4b, 0xda, 0x35, 0xa5,
	0x25, 0x24, 0x6f, 0x60, 0xef, 0xb6, 0x2c, 0xb8, 0x12, 0xbc, 0x0d, 0x89, 0x76, 0x6f, 0xed, 0xf0,
	0xee, 0x94, 0x06, 0xf7, 0xfe, 0xac, 0xc0, 0xfa, 0x30, 0x9c, 0x9f, 0x7c, 0x80, 0xb6, 0xf3, 0x75,
	0xd4, 0x4e, 0x45, 0xde, 0xa9, 0xde, 0x5d, 0x4e, 0x55, 0xfe, 0xc4, 0x6e, 0xf1, 0xf6, 0xec, 0xc2,
	0x5a, 0x38, 0x71, 0x95, 0xbc, 0x9a, 0x2d, 0x6f, 0x47, 0xe3, 0x7f, 0xb4, 0x83, 0x9c, 0xc2, 0x4e,
	0x55, 0x7b, 0xe5, 0x7f, 0x15, 0x7d, 0xb5, 0xdb, 0xe8, 0xb7, 0x0e, 0xfa, 0x77, 0x45, 0x5f, 0x6c,
	0x20, 0x25, 0xee, 0xdf, 0xa6, 0xbe, 0x87, 0x0d, 0xbc, 0xd2, 0xc8, 0x1d, 0xe6, 0x99, 0x7f, 0x9e,
	0xfe, 0x3a, 0xb6, 0x0e, 0x9e, 0x2c, 0x8f, 0x3a, 0x7f, 0xe4, 0xb4, 0x5d, 0x6f, 0xf3, 0xe8, 0xd0,
	0x9e, 0xfe, 0x38, 0x17, 0x6e, 0x3c, 0x1d, 0x25, 0x5c, 0x4d, 0xd2, 0x77, 0x85, 0x9a, 0xe6, 0x83,
	0x93, 0xe1, 0x51, 0x5a, 0x47, 0x19, 0x4c, 0x54, 0x3e, 0x2d, 0xd0, 0x0e, 0xb4, 0x51, 0xdf, 0x91,
	0xbb, 0xd4, 0x19, 0x26, 0x2d, 0x57, 0x39, 0x0e, 0x2e, 0x95, 0xb9, 0x40, 0x33, 0x90, 0x2a, 0xc7,
	0xd4, 0x7f, 0x32, 0x29, 0x2f, 0x84, 0xff, 0x7b, 0x96, 0xfd, 0x46, 0x6f, 0xeb, 0xf1, 0x6c, 0x7f,
	0xb4, 0xe6, 0xe5, 0xaf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xbf, 0xef, 0x2f, 0xb7, 0x04,
	0x00, 0x00,
}
