// Code generated by protoc-gen-go. DO NOT EDIT.
// source: livepeer/registry/v1/publisher.proto

package registryv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildManifestRequest struct {
	Nodes                []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	ExpiresAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BuildManifestRequest) Reset()         { *m = BuildManifestRequest{} }
func (m *BuildManifestRequest) String() string { return proto.CompactTextString(m) }
func (*BuildManifestRequest) ProtoMessage()    {}
func (*BuildManifestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40273fe0be635c70, []int{0}
}

func (m *BuildManifestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildManifestRequest.Unmarshal(m, b)
}
func (m *BuildManifestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildManifestRequest.Marshal(b, m, deterministic)
}
func (m *BuildManifestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildManifestRequest.Merge(m, src)
}
func (m *BuildManifestRequest) XXX_Size() int {
	return xxx_messageInfo_BuildManifestRequest.Size(m)
}
func (m *BuildManifestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildManifestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildManifestRequest proto.InternalMessageInfo

func (m *BuildManifestRequest) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *BuildManifestRequest) GetExpiresAt() *timestamppb.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

type BuildResult struct {
	ManifestJson         []byte   `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	CanonicalBytes       []byte   `protobuf:"bytes,2,opt,name=canonical_bytes,json=canonicalBytes,proto3" json:"canonical_bytes,omitempty"`
	CanonicalSha256      string   `protobuf:"bytes,3,opt,name=canonical_sha256,json=canonicalSha256,proto3" json:"canonical_sha256,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildResult) Reset()         { *m = BuildResult{} }
func (m *BuildResult) String() string { return proto.CompactTextString(m) }
func (*BuildResult) ProtoMessage()    {}
func (*BuildResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40273fe0be635c70, []int{1}
}

func (m *BuildResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildResult.Unmarshal(m, b)
}
func (m *BuildResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildResult.Marshal(b, m, deterministic)
}
func (m *BuildResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildResult.Merge(m, src)
}
func (m *BuildResult) XXX_Size() int {
	return xxx_messageInfo_BuildResult.Size(m)
}
func (m *BuildResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildResult.DiscardUnknown(m)
}

var xxx_messageInfo_BuildResult proto.InternalMessageInfo

func (m *BuildResult) GetManifestJson() []byte {
	if m != nil {
		return m.ManifestJson
	}
	return nil
}

func (m *BuildResult) GetCanonicalBytes() []byte {
	if m != nil {
		return m.CanonicalBytes
	}
	return nil
}

func (m *BuildResult) GetCanonicalSha256() string {
	if m != nil {
		return m.CanonicalSha256
	}
	return ""
}

type SignManifestRequest struct {
	ManifestJson         []byte   `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignManifestRequest) Reset()         { *m = SignManifestRequest{} }
func (m *SignManifestRequest) String() string { return proto.CompactTextString(m) }
func (*SignManifestRequest) ProtoMessage()    {}
func (*SignManifestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40273fe0be635c70, []int{2}
}

func (m *SignManifestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignManifestRequest.Unmarshal(m, b)
}
func (m *SignManifestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignManifestRequest.Marshal(b, m, deterministic)
}
func (m *SignManifestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignManifestRequest.Merge(m, src)
}
func (m *SignManifestRequest) XXX_Size() int {
	return xxx_messageInfo_SignManifestRequest.Size(m)
}
func (m *SignManifestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignManifestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignManifestRequest proto.InternalMessageInfo

func (m *SignManifestRequest) GetManifestJson() []byte {
	if m != nil {
		return m.ManifestJson
	}
	return nil
}

type SignedManifest struct {
	ManifestJson         []byte   `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	SignatureValue       string   `protobuf:"bytes,2,opt,name=signature_value,json=signatureValue,proto3" json:"signature_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedManifest) Reset()         { *m = SignedManifest{} }
func (m *SignedManifest) String() string { return proto.CompactTextString(m) }
func (*SignedManifest) ProtoMessage()    {}
func (*SignedManifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40273fe0be635c70, []int{3}
}

func (m *SignedManifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedManifest.Unmarshal(m, b)
}
func (m *SignedManifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedManifest.Marshal(b, m, deterministic)
}
func (m *SignedManifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedManifest.Merge(m, src)
}
func (m *SignedManifest) XXX_Size() int {
	return xxx_messageInfo_SignedManifest.Size(m)
}
func (m *SignedManifest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedManifest.DiscardUnknown(m)
}

var xxx_messageInfo_SignedManifest proto.InternalMessageInfo

func (m *SignedManifest) GetManifestJson() []byte {
	if m != nil {
		return m.ManifestJson
	}
	return nil
}

func (m *SignedManifest) GetSignatureValue() string {
	if m != nil {
		return m.SignatureValue
	}
	return ""
}

type WriteServiceURIRequest struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteServiceURIRequest) Reset()         { *m = WriteServiceURIRequest{} }
func (m *WriteServiceURIRequest) String() string { return proto.CompactTextString(m) }
func (*WriteServiceURIRequest) ProtoMessage()    {}
func (*WriteServiceURIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40273fe0be635c70, []int{4}
}

func (m *WriteServiceURIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteServiceURIRequest.Unmarshal(m, b)
}
func (m *WriteServiceURIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteServiceURIRequest.Marshal(b, m, deterministic)
}
func (m *WriteServiceURIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteServiceURIRequest.Merge(m, src)
}
func (m *WriteServiceURIRequest) XXX_Size() int {
	return xxx_messageInfo_WriteServiceURIRequest.Size(m)
}
func (m *WriteServiceURIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteServiceURIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteServiceURIRequest proto.InternalMessageInfo

func (m *WriteServiceURIRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type TxHashResult struct {
	TxHash               string   `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxHashResult) Reset()         { *m = TxHashResult{} }
func (m *TxHashResult) String() string { return proto.CompactTextString(m) }
func (*TxHashResult) ProtoMessage()    {}
func (*TxHashResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40273fe0be635c70, []int{5}
}

func (m *TxHashResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxHashResult.Unmarshal(m, b)
}
func (m *TxHashResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxHashResult.Marshal(b, m, deterministic)
}
func (m *TxHashResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxHashResult.Merge(m, src)
}
func (m *TxHashResult) XXX_Size() int {
	return xxx_messageInfo_TxHashResult.Size(m)
}
func (m *TxHashResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TxHashResult.DiscardUnknown(m)
}

var xxx_messageInfo_TxHashResult proto.InternalMessageInfo

func (m *TxHashResult) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type ProbeWorkerRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	TimeoutSeconds       int32    `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeWorkerRequest) Reset()         { *m = ProbeWorkerRequest{} }
func (m *ProbeWorkerRequest) String() string { return proto.CompactTextString(m) }
func (*ProbeWorkerRequest) ProtoMessage()    {}
func (*ProbeWorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40273fe0be635c70, []int{6}
}

func (m *ProbeWorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeWorkerRequest.Unmarshal(m, b)
}
func (m *ProbeWorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeWorkerRequest.Marshal(b, m, deterministic)
}
func (m *ProbeWorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeWorkerRequest.Merge(m, src)
}
func (m *ProbeWorkerRequest) XXX_Size() int {
	return xxx_messageInfo_ProbeWorkerRequest.Size(m)
}
func (m *ProbeWorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeWorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeWorkerRequest proto.InternalMessageInfo

func (m *ProbeWorkerRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProbeWorkerRequest) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

type ProbeResult struct {
	CapabilitiesJson     []byte   `protobuf:"bytes,1,opt,name=capabilities_json,json=capabilitiesJson,proto3" json:"capabilities_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbeResult) Reset()         { *m = ProbeResult{} }
func (m *ProbeResult) String() string { return proto.CompactTextString(m) }
func (*ProbeResult) ProtoMessage()    {}
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40273fe0be635c70, []int{7}
}

func (m *ProbeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbeResult.Unmarshal(m, b)
}
func (m *ProbeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbeResult.Marshal(b, m, deterministic)
}
func (m *ProbeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbeResult.Merge(m, src)
}
func (m *ProbeResult) XXX_Size() int {
	return xxx_messageInfo_ProbeResult.Size(m)
}
func (m *ProbeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbeResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProbeResult proto.InternalMessageInfo

func (m *ProbeResult) GetCapabilitiesJson() []byte {
	if m != nil {
		return m.CapabilitiesJson
	}
	return nil
}

func init() {
	proto.RegisterType((*BuildManifestRequest)(nil), "livepeer.registry.v1.BuildManifestRequest")
	proto.RegisterType((*BuildResult)(nil), "livepeer.registry.v1.BuildResult")
	proto.RegisterType((*SignManifestRequest)(nil), "livepeer.registry.v1.SignManifestRequest")
	proto.RegisterType((*SignedManifest)(nil), "livepeer.registry.v1.SignedManifest")
	proto.RegisterType((*WriteServiceURIRequest)(nil), "livepeer.registry.v1.WriteServiceURIRequest")
	proto.RegisterType((*TxHashResult)(nil), "livepeer.registry.v1.TxHashResult")
	proto.RegisterType((*ProbeWorkerRequest)(nil), "livepeer.registry.v1.ProbeWorkerRequest")
	proto.RegisterType((*ProbeResult)(nil), "livepeer.registry.v1.ProbeResult")
}

func init() {
	proto.RegisterFile("livepeer/registry/v1/publisher.proto", fileDescriptor_40273fe0be635c70)
}

var fileDescriptor_40273fe0be635c70 = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5f, 0x4f, 0xd4, 0x4e,
	0x14, 0x4d, 0x7f, 0x1b, 0xf8, 0x65, 0x87, 0x65, 0xc1, 0x91, 0xe0, 0xa6, 0x3e, 0xb8, 0x16, 0x12,
	0x16, 0x74, 0x5b, 0xc1, 0x68, 0x22, 0x3e, 0x89, 0x92, 0xa0, 0x89, 0x4a, 0xba, 0x28, 0x09, 0x0f,
	0x34, 0xd3, 0xf6, 0xb2, 0x1d, 0x9c, 0x76, 0xca, 0xcc, 0xb4, 0xb2, 0xcf, 0x26, 0x7e, 0x41, 0xbf,
	0x90, 0xe9, 0x3f, 0x58, 0x60, 0xd6, 0xf0, 0xd6, 0xdc, 0x39, 0xe7, 0xce, 0xb9, 0xe7, 0xdc, 0x0e,
	0x5a, 0x67, 0x34, 0x87, 0x14, 0x40, 0x38, 0x02, 0xc6, 0x54, 0x2a, 0x31, 0x71, 0xf2, 0x6d, 0x27,
	0xcd, 0x7c, 0x46, 0x65, 0x04, 0xc2, 0x4e, 0x05, 0x57, 0x1c, 0xaf, 0x34, 0x28, 0xbb, 0x41, 0xd9,
	0xf9, 0xb6, 0xf9, 0x78, 0xcc, 0xf9, 0x98, 0x81, 0x53, 0x62, 0xfc, 0xec, 0xcc, 0x81, 0x38, 0x55,
	0x93, 0x8a, 0x62, 0x3e, 0xb9, 0x7d, 0xa8, 0x68, 0x0c, 0x52, 0x91, 0x38, 0xad, 0x01, 0x6b, 0xda,
	0x9b, 0x05, 0x48, 0xce, 0xf2, 0xe6, 0x62, 0xb3, 0xaf, 0x05, 0xa9, 0x49, 0x0a, 0xb2, 0x42, 0x58,
	0xbf, 0x0c, 0xb4, 0xb2, 0x97, 0x51, 0x16, 0x7e, 0x26, 0x09, 0x3d, 0x03, 0xa9, 0x5c, 0xb8, 0xc8,
	0x40, 0x2a, 0xfc, 0x02, 0xcd, 0x25, 0x3c, 0x04, 0xd9, 0x33, 0xfa, 0xad, 0xc1, 0xc2, 0x8e, 0x69,
	0xeb, 0x66, 0xb0, 0xbf, 0xf0, 0x10, 0xdc, 0x0a, 0x88, 0xdf, 0x20, 0x04, 0x97, 0x29, 0x15, 0x20,
	0x3d, 0xa2, 0x7a, 0xff, 0xf5, 0x8d, 0x92, 0x56, 0xcd, 0x61, 0x37, 0x73, 0xd8, 0x47, 0xcd, 0x1c,
	0x6e, 0xbb, 0x46, 0xbf, 0x53, 0xd6, 0x6f, 0x03, 0x2d, 0x94, 0x2a, 0x5c, 0x90, 0x19, 0x53, 0x78,
	0x0d, 0x2d, 0xc6, 0xb5, 0x1e, 0xef, 0x5c, 0xf2, 0xa4, 0x67, 0xf4, 0x8d, 0x41, 0xc7, 0xed, 0x34,
	0xc5, 0x4f, 0x92, 0x27, 0x78, 0x03, 0x2d, 0x05, 0x24, 0xe1, 0x09, 0x0d, 0x08, 0xf3, 0xfc, 0x89,
	0x02, 0x59, 0x5e, 0xda, 0x71, 0xbb, 0x57, 0xe5, 0xbd, 0xa2, 0x8a, 0x37, 0xd1, 0xf2, 0x35, 0x50,
	0x46, 0x64, 0xe7, 0xd5, 0xeb, 0x5e, 0xab, 0x6f, 0x0c, 0xda, 0xee, 0x75, 0x83, 0x51, 0x59, 0xb6,
	0x76, 0xd1, 0xc3, 0x11, 0x1d, 0x27, 0xb7, 0xcd, 0xb8, 0x8f, 0x1e, 0xeb, 0x14, 0x75, 0x0b, 0x2e,
	0x5c, 0x59, 0x79, 0xef, 0x31, 0x24, 0x1d, 0x27, 0x44, 0x65, 0x02, 0xbc, 0x9c, 0xb0, 0x0c, 0xca,
	0x31, 0xda, 0x6e, 0xf7, 0xaa, 0xfc, 0xbd, 0xa8, 0x5a, 0x5b, 0x68, 0xf5, 0x58, 0x50, 0x05, 0x23,
	0x10, 0x39, 0x0d, 0xe0, 0x9b, 0xfb, 0xb1, 0x91, 0xb7, 0x8c, 0x5a, 0x99, 0xa0, 0x65, 0xf7, 0xb6,
	0x5b, 0x7c, 0x5a, 0x1b, 0xa8, 0x73, 0x74, 0x79, 0x40, 0x64, 0x54, 0x1b, 0xfa, 0x08, 0xfd, 0xaf,
	0x2e, 0xbd, 0x88, 0xc8, 0xa8, 0x46, 0xcd, 0xab, 0xf2, 0xd8, 0xfa, 0x8a, 0xf0, 0xa1, 0xe0, 0x3e,
	0x1c, 0x73, 0xf1, 0x03, 0xc4, 0x8d, 0x86, 0xec, 0xba, 0x21, 0x2b, 0x54, 0x16, 0x1b, 0xc8, 0x33,
	0xe5, 0x49, 0x08, 0x78, 0x12, 0x56, 0x66, 0xcf, 0xb9, 0xdd, 0xba, 0x3c, 0xaa, 0xaa, 0xd6, 0x2e,
	0x5a, 0x28, 0x1b, 0xd6, 0x17, 0x3f, 0x43, 0x0f, 0x02, 0x92, 0x12, 0x9f, 0x32, 0xaa, 0x28, 0xc8,
	0x69, 0x1b, 0x96, 0xa7, 0x0f, 0x0a, 0x2b, 0x76, 0xfe, 0xb4, 0x50, 0xfb, 0xb0, 0xf9, 0x77, 0xf0,
	0x29, 0x5a, 0xbc, 0xb1, 0x99, 0x78, 0x4b, 0xbf, 0x83, 0xba, 0xf5, 0x35, 0x9f, 0xfe, 0x03, 0x5b,
	0x4b, 0xf3, 0x50, 0x67, 0x3a, 0x6b, 0xbc, 0xa9, 0xa7, 0x68, 0xf6, 0xc1, 0x5c, 0x9f, 0x0d, 0x9d,
	0x8a, 0x3f, 0x40, 0x4b, 0xb7, 0x02, 0xc3, 0xcf, 0xf5, 0x44, 0x7d, 0xae, 0xa6, 0xa5, 0x47, 0xdf,
	0x48, 0xf6, 0xa4, 0xf6, 0xbb, 0x0a, 0x10, 0x0f, 0xf4, 0x94, 0xbb, 0x19, 0xcf, 0x72, 0x68, 0x3a,
	0xbc, 0x0f, 0x68, 0xfe, 0x00, 0x08, 0x53, 0x11, 0x5e, 0xbd, 0xf3, 0x1f, 0xef, 0x17, 0x8f, 0xd5,
	0x2c, 0x85, 0x15, 0xab, 0xea, 0xb2, 0x27, 0x4f, 0x2e, 0xc6, 0x54, 0x45, 0x99, 0x6f, 0x07, 0x3c,
	0x76, 0xde, 0x33, 0x9e, 0x85, 0xc3, 0xd1, 0xe1, 0xbe, 0xd3, 0x30, 0x87, 0x31, 0x0f, 0x33, 0x06,
	0x72, 0x98, 0x0a, 0x7e, 0x0e, 0x81, 0x72, 0x94, 0x20, 0x89, 0x0c, 0x78, 0x08, 0xc3, 0x9f, 0xa5,
	0xe2, 0x61, 0xf1, 0xbe, 0x54, 0x2f, 0xa1, 0x13, 0x30, 0x0a, 0x89, 0x92, 0x8e, 0xee, 0x61, 0x7b,
	0xdb, 0x7c, 0xe7, 0xdb, 0xfe, 0x7c, 0x09, 0x7f, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x56, 0x53,
	0x7b, 0x41, 0xa1, 0x05, 0x00, 0x00,
}
