// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: livepeer/registry/v1/publisher.proto

package registryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Publisher_BuildManifest_FullMethodName   = "/livepeer.registry.v1.Publisher/BuildManifest"
	Publisher_SignManifest_FullMethodName    = "/livepeer.registry.v1.Publisher/SignManifest"
	Publisher_WriteServiceURI_FullMethodName = "/livepeer.registry.v1.Publisher/WriteServiceURI"
	Publisher_ProbeWorker_FullMethodName     = "/livepeer.registry.v1.Publisher/ProbeWorker"
	Publisher_Health_FullMethodName          = "/livepeer.registry.v1.Publisher/Health"
)

// PublisherClient is the client API for Publisher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublisherClient interface {
	BuildManifest(ctx context.Context, in *BuildManifestRequest, opts ...grpc.CallOption) (*BuildResult, error)
	SignManifest(ctx context.Context, in *SignManifestRequest, opts ...grpc.CallOption) (*SignedManifest, error)
	WriteServiceURI(ctx context.Context, in *WriteServiceURIRequest, opts ...grpc.CallOption) (*TxHashResult, error)
	ProbeWorker(ctx context.Context, in *ProbeWorkerRequest, opts ...grpc.CallOption) (*ProbeResult, error)
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResult, error)
}

type publisherClient struct {
	cc grpc.ClientConnInterface
}

func NewPublisherClient(cc grpc.ClientConnInterface) PublisherClient {
	return &publisherClient{cc}
}

func (c *publisherClient) BuildManifest(ctx context.Context, in *BuildManifestRequest, opts ...grpc.CallOption) (*BuildResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResult)
	err := c.cc.Invoke(ctx, Publisher_BuildManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) SignManifest(ctx context.Context, in *SignManifestRequest, opts ...grpc.CallOption) (*SignedManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedManifest)
	err := c.cc.Invoke(ctx, Publisher_SignManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) WriteServiceURI(ctx context.Context, in *WriteServiceURIRequest, opts ...grpc.CallOption) (*TxHashResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxHashResult)
	err := c.cc.Invoke(ctx, Publisher_WriteServiceURI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) ProbeWorker(ctx context.Context, in *ProbeWorkerRequest, opts ...grpc.CallOption) (*ProbeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeResult)
	err := c.cc.Invoke(ctx, Publisher_ProbeWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResult)
	err := c.cc.Invoke(ctx, Publisher_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublisherServer is the server API for Publisher service.
// All implementations should embed UnimplementedPublisherServer
// for forward compatibility.
type PublisherServer interface {
	BuildManifest(context.Context, *BuildManifestRequest) (*BuildResult, error)
	SignManifest(context.Context, *SignManifestRequest) (*SignedManifest, error)
	WriteServiceURI(context.Context, *WriteServiceURIRequest) (*TxHashResult, error)
	ProbeWorker(context.Context, *ProbeWorkerRequest) (*ProbeResult, error)
	Health(context.Context, *emptypb.Empty) (*HealthResult, error)
}

// UnimplementedPublisherServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublisherServer struct{}

func (UnimplementedPublisherServer) BuildManifest(context.Context, *BuildManifestRequest) (*BuildResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildManifest not implemented")
}
func (UnimplementedPublisherServer) SignManifest(context.Context, *SignManifestRequest) (*SignedManifest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignManifest not implemented")
}
func (UnimplementedPublisherServer) WriteServiceURI(context.Context, *WriteServiceURIRequest) (*TxHashResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteServiceURI not implemented")
}
func (UnimplementedPublisherServer) ProbeWorker(context.Context, *ProbeWorkerRequest) (*ProbeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProbeWorker not implemented")
}
func (UnimplementedPublisherServer) Health(context.Context, *emptypb.Empty) (*HealthResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPublisherServer) testEmbeddedByValue() {}

// UnsafePublisherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublisherServer will
// result in compilation errors.
type UnsafePublisherServer interface {
	mustEmbedUnimplementedPublisherServer()
}

func RegisterPublisherServer(s grpc.ServiceRegistrar, srv PublisherServer) {
	// If the following call pancis, it indicates UnimplementedPublisherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Publisher_ServiceDesc, srv)
}

func _Publisher_BuildManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).BuildManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Publisher_BuildManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).BuildManifest(ctx, req.(*BuildManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_SignManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).SignManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Publisher_SignManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).SignManifest(ctx, req.(*SignManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_WriteServiceURI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteServiceURIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).WriteServiceURI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Publisher_WriteServiceURI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).WriteServiceURI(ctx, req.(*WriteServiceURIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_ProbeWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).ProbeWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Publisher_ProbeWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).ProbeWorker(ctx, req.(*ProbeWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Publisher_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Publisher_ServiceDesc is the grpc.ServiceDesc for Publisher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Publisher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livepeer.registry.v1.Publisher",
	HandlerType: (*PublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuildManifest",
			Handler:    _Publisher_BuildManifest_Handler,
		},
		{
			MethodName: "SignManifest",
			Handler:    _Publisher_SignManifest_Handler,
		},
		{
			MethodName: "WriteServiceURI",
			Handler:    _Publisher_WriteServiceURI_Handler,
		},
		{
			MethodName: "ProbeWorker",
			Handler:    _Publisher_ProbeWorker_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Publisher_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livepeer/registry/v1/publisher.proto",
}
