// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: livepeer/registry/v1/resolver.proto

package registryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Resolver_ResolveByAddress_FullMethodName = "/livepeer.registry.v1.Resolver/ResolveByAddress"
	Resolver_Select_FullMethodName           = "/livepeer.registry.v1.Resolver/Select"
	Resolver_ListKnown_FullMethodName        = "/livepeer.registry.v1.Resolver/ListKnown"
	Resolver_Refresh_FullMethodName          = "/livepeer.registry.v1.Resolver/Refresh"
	Resolver_GetAuditLog_FullMethodName      = "/livepeer.registry.v1.Resolver/GetAuditLog"
	Resolver_Health_FullMethodName           = "/livepeer.registry.v1.Resolver/Health"
)

// ResolverClient is the client API for Resolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResolverClient interface {
	ResolveByAddress(ctx context.Context, in *ResolveByAddressRequest, opts ...grpc.CallOption) (*ResolveResult, error)
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResult, error)
	ListKnown(ctx context.Context, in *ListKnownRequest, opts ...grpc.CallOption) (*ListKnownResult, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*AuditLogResult, error)
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResult, error)
}

type resolverClient struct {
	cc grpc.ClientConnInterface
}

func NewResolverClient(cc grpc.ClientConnInterface) ResolverClient {
	return &resolverClient{cc}
}

func (c *resolverClient) ResolveByAddress(ctx context.Context, in *ResolveByAddressRequest, opts ...grpc.CallOption) (*ResolveResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResult)
	err := c.cc.Invoke(ctx, Resolver_ResolveByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectResult)
	err := c.cc.Invoke(ctx, Resolver_Select_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) ListKnown(ctx context.Context, in *ListKnownRequest, opts ...grpc.CallOption) (*ListKnownResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKnownResult)
	err := c.cc.Invoke(ctx, Resolver_ListKnown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Resolver_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*AuditLogResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditLogResult)
	err := c.cc.Invoke(ctx, Resolver_GetAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResult)
	err := c.cc.Invoke(ctx, Resolver_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResolverServer is the server API for Resolver service.
// All implementations should embed UnimplementedResolverServer
// for forward compatibility.
type ResolverServer interface {
	ResolveByAddress(context.Context, *ResolveByAddressRequest) (*ResolveResult, error)
	Select(context.Context, *SelectRequest) (*SelectResult, error)
	ListKnown(context.Context, *ListKnownRequest) (*ListKnownResult, error)
	Refresh(context.Context, *RefreshRequest) (*emptypb.Empty, error)
	GetAuditLog(context.Context, *GetAuditLogRequest) (*AuditLogResult, error)
	Health(context.Context, *emptypb.Empty) (*HealthResult, error)
}

// UnimplementedResolverServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResolverServer struct{}

func (UnimplementedResolverServer) ResolveByAddress(context.Context, *ResolveByAddressRequest) (*ResolveResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveByAddress not implemented")
}
func (UnimplementedResolverServer) Select(context.Context, *SelectRequest) (*SelectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Select not implemented")
}
func (UnimplementedResolverServer) ListKnown(context.Context, *ListKnownRequest) (*ListKnownResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKnown not implemented")
}
func (UnimplementedResolverServer) Refresh(context.Context, *RefreshRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedResolverServer) GetAuditLog(context.Context, *GetAuditLogRequest) (*AuditLogResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditLog not implemented")
}
func (UnimplementedResolverServer) Health(context.Context, *emptypb.Empty) (*HealthResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedResolverServer) testEmbeddedByValue() {}

// UnsafeResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResolverServer will
// result in compilation errors.
type UnsafeResolverServer interface {
	mustEmbedUnimplementedResolverServer()
}

func RegisterResolverServer(s grpc.ServiceRegistrar, srv ResolverServer) {
	// If the following call pancis, it indicates UnimplementedResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Resolver_ServiceDesc, srv)
}

func _Resolver_ResolveByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ResolveByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ResolveByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ResolveByAddress(ctx, req.(*ResolveByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_Select_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_ListKnown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKnownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ListKnown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ListKnown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ListKnown(ctx, req.(*ListKnownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_GetAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).GetAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_GetAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).GetAuditLog(ctx, req.(*GetAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Resolver_ServiceDesc is the grpc.ServiceDesc for Resolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "livepeer.registry.v1.Resolver",
	HandlerType: (*ResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveByAddress",
			Handler:    _Resolver_ResolveByAddress_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _Resolver_Select_Handler,
		},
		{
			MethodName: "ListKnown",
			Handler:    _Resolver_ListKnown_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Resolver_Refresh_Handler,
		},
		{
			MethodName: "GetAuditLog",
			Handler:    _Resolver_GetAuditLog_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Resolver_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livepeer/registry/v1/resolver.proto",
}
