// Code generated by protoc-gen-go. DO NOT EDIT.
// source: livepeer/registry/v1/resolver.proto

package registryv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResolveByAddressRequest struct {
	EthAddress           string   `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	AllowLegacyFallback  bool     `protobuf:"varint,2,opt,name=allow_legacy_fallback,json=allowLegacyFallback,proto3" json:"allow_legacy_fallback,omitempty"`
	AllowUnsigned        bool     `protobuf:"varint,3,opt,name=allow_unsigned,json=allowUnsigned,proto3" json:"allow_unsigned,omitempty"`
	ForceRefresh         bool     `protobuf:"varint,4,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveByAddressRequest) Reset()         { *m = ResolveByAddressRequest{} }
func (m *ResolveByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveByAddressRequest) ProtoMessage()    {}
func (*ResolveByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{0}
}

func (m *ResolveByAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveByAddressRequest.Unmarshal(m, b)
}
func (m *ResolveByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveByAddressRequest.Marshal(b, m, deterministic)
}
func (m *ResolveByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveByAddressRequest.Merge(m, src)
}
func (m *ResolveByAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveByAddressRequest.Size(m)
}
func (m *ResolveByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveByAddressRequest proto.InternalMessageInfo

func (m *ResolveByAddressRequest) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *ResolveByAddressRequest) GetAllowLegacyFallback() bool {
	if m != nil {
		return m.AllowLegacyFallback
	}
	return false
}

func (m *ResolveByAddressRequest) GetAllowUnsigned() bool {
	if m != nil {
		return m.AllowUnsigned
	}
	return false
}

func (m *ResolveByAddressRequest) GetForceRefresh() bool {
	if m != nil {
		return m.ForceRefresh
	}
	return false
}

type ResolveResult struct {
	EthAddress           string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	ResolvedUri          string                 `protobuf:"bytes,2,opt,name=resolved_uri,json=resolvedUri,proto3" json:"resolved_uri,omitempty"`
	Mode                 ResolveMode            `protobuf:"varint,3,opt,name=mode,proto3,enum=livepeer.registry.v1.ResolveMode" json:"mode,omitempty"`
	Nodes                []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	FreshnessStatus      FreshnessStatus        `protobuf:"varint,5,opt,name=freshness_status,json=freshnessStatus,proto3,enum=livepeer.registry.v1.FreshnessStatus" json:"freshness_status,omitempty"`
	CachedAt             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	FetchedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	SchemaVersion        int32                  `protobuf:"varint,8,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ResolveResult) Reset()         { *m = ResolveResult{} }
func (m *ResolveResult) String() string { return proto.CompactTextString(m) }
func (*ResolveResult) ProtoMessage()    {}
func (*ResolveResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{1}
}

func (m *ResolveResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveResult.Unmarshal(m, b)
}
func (m *ResolveResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveResult.Marshal(b, m, deterministic)
}
func (m *ResolveResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveResult.Merge(m, src)
}
func (m *ResolveResult) XXX_Size() int {
	return xxx_messageInfo_ResolveResult.Size(m)
}
func (m *ResolveResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveResult.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveResult proto.InternalMessageInfo

func (m *ResolveResult) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *ResolveResult) GetResolvedUri() string {
	if m != nil {
		return m.ResolvedUri
	}
	return ""
}

func (m *ResolveResult) GetMode() ResolveMode {
	if m != nil {
		return m.Mode
	}
	return ResolveMode_RESOLVE_MODE_UNSPECIFIED
}

func (m *ResolveResult) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ResolveResult) GetFreshnessStatus() FreshnessStatus {
	if m != nil {
		return m.FreshnessStatus
	}
	return FreshnessStatus_FRESHNESS_UNSPECIFIED
}

func (m *ResolveResult) GetCachedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CachedAt
	}
	return nil
}

func (m *ResolveResult) GetFetchedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.FetchedAt
	}
	return nil
}

func (m *ResolveResult) GetSchemaVersion() int32 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

type SelectRequest struct {
	Capability           string   `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	Model                string   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Tier                 string   `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	MinWeight            int32    `protobuf:"varint,4,opt,name=min_weight,json=minWeight,proto3" json:"min_weight,omitempty"`
	GeoLat               float64  `protobuf:"fixed64,5,opt,name=geo_lat,json=geoLat,proto3" json:"geo_lat,omitempty"`
	GeoLon               float64  `protobuf:"fixed64,6,opt,name=geo_lon,json=geoLon,proto3" json:"geo_lon,omitempty"`
	GeoWithinKm          float64  `protobuf:"fixed64,7,opt,name=geo_within_km,json=geoWithinKm,proto3" json:"geo_within_km,omitempty"`
	HasGeo               bool     `protobuf:"varint,8,opt,name=has_geo,json=hasGeo,proto3" json:"has_geo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectRequest) Reset()         { *m = SelectRequest{} }
func (m *SelectRequest) String() string { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()    {}
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{2}
}

func (m *SelectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectRequest.Unmarshal(m, b)
}
func (m *SelectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectRequest.Marshal(b, m, deterministic)
}
func (m *SelectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectRequest.Merge(m, src)
}
func (m *SelectRequest) XXX_Size() int {
	return xxx_messageInfo_SelectRequest.Size(m)
}
func (m *SelectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectRequest proto.InternalMessageInfo

func (m *SelectRequest) GetCapability() string {
	if m != nil {
		return m.Capability
	}
	return ""
}

func (m *SelectRequest) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *SelectRequest) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

func (m *SelectRequest) GetMinWeight() int32 {
	if m != nil {
		return m.MinWeight
	}
	return 0
}

func (m *SelectRequest) GetGeoLat() float64 {
	if m != nil {
		return m.GeoLat
	}
	return 0
}

func (m *SelectRequest) GetGeoLon() float64 {
	if m != nil {
		return m.GeoLon
	}
	return 0
}

func (m *SelectRequest) GetGeoWithinKm() float64 {
	if m != nil {
		return m.GeoWithinKm
	}
	return 0
}

func (m *SelectRequest) GetHasGeo() bool {
	if m != nil {
		return m.HasGeo
	}
	return false
}

type SelectResult struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectResult) Reset()         { *m = SelectResult{} }
func (m *SelectResult) String() string { return proto.CompactTextString(m) }
func (*SelectResult) ProtoMessage()    {}
func (*SelectResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{3}
}

func (m *SelectResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectResult.Unmarshal(m, b)
}
func (m *SelectResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectResult.Marshal(b, m, deterministic)
}
func (m *SelectResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectResult.Merge(m, src)
}
func (m *SelectResult) XXX_Size() int {
	return xxx_messageInfo_SelectResult.Size(m)
}
func (m *SelectResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectResult.DiscardUnknown(m)
}

var xxx_messageInfo_SelectResult proto.InternalMessageInfo

func (m *SelectResult) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type ListKnownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListKnownRequest) Reset()         { *m = ListKnownRequest{} }
func (m *ListKnownRequest) String() string { return proto.CompactTextString(m) }
func (*ListKnownRequest) ProtoMessage()    {}
func (*ListKnownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{4}
}

func (m *ListKnownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKnownRequest.Unmarshal(m, b)
}
func (m *ListKnownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKnownRequest.Marshal(b, m, deterministic)
}
func (m *ListKnownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKnownRequest.Merge(m, src)
}
func (m *ListKnownRequest) XXX_Size() int {
	return xxx_messageInfo_ListKnownRequest.Size(m)
}
func (m *ListKnownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKnownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListKnownRequest proto.InternalMessageInfo

type ListKnownResult struct {
	Entries              []*KnownEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListKnownResult) Reset()         { *m = ListKnownResult{} }
func (m *ListKnownResult) String() string { return proto.CompactTextString(m) }
func (*ListKnownResult) ProtoMessage()    {}
func (*ListKnownResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{5}
}

func (m *ListKnownResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKnownResult.Unmarshal(m, b)
}
func (m *ListKnownResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKnownResult.Marshal(b, m, deterministic)
}
func (m *ListKnownResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKnownResult.Merge(m, src)
}
func (m *ListKnownResult) XXX_Size() int {
	return xxx_messageInfo_ListKnownResult.Size(m)
}
func (m *ListKnownResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKnownResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListKnownResult proto.InternalMessageInfo

func (m *ListKnownResult) GetEntries() []*KnownEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type KnownEntry struct {
	EthAddress           string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Mode                 ResolveMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=livepeer.registry.v1.ResolveMode" json:"mode,omitempty"`
	FreshnessStatus      FreshnessStatus        `protobuf:"varint,3,opt,name=freshness_status,json=freshnessStatus,proto3,enum=livepeer.registry.v1.FreshnessStatus" json:"freshness_status,omitempty"`
	CachedAt             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *KnownEntry) Reset()         { *m = KnownEntry{} }
func (m *KnownEntry) String() string { return proto.CompactTextString(m) }
func (*KnownEntry) ProtoMessage()    {}
func (*KnownEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{6}
}

func (m *KnownEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KnownEntry.Unmarshal(m, b)
}
func (m *KnownEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KnownEntry.Marshal(b, m, deterministic)
}
func (m *KnownEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KnownEntry.Merge(m, src)
}
func (m *KnownEntry) XXX_Size() int {
	return xxx_messageInfo_KnownEntry.Size(m)
}
func (m *KnownEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_KnownEntry.DiscardUnknown(m)
}

var xxx_messageInfo_KnownEntry proto.InternalMessageInfo

func (m *KnownEntry) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *KnownEntry) GetMode() ResolveMode {
	if m != nil {
		return m.Mode
	}
	return ResolveMode_RESOLVE_MODE_UNSPECIFIED
}

func (m *KnownEntry) GetFreshnessStatus() FreshnessStatus {
	if m != nil {
		return m.FreshnessStatus
	}
	return FreshnessStatus_FRESHNESS_UNSPECIFIED
}

func (m *KnownEntry) GetCachedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CachedAt
	}
	return nil
}

type RefreshRequest struct {
	EthAddress           string   `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Force                bool     `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{7}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

func (m *RefreshRequest) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *RefreshRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type GetAuditLogRequest struct {
	EthAddress           string                 `protobuf:"bytes,1,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Since                *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Limit                int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetAuditLogRequest) Reset()         { *m = GetAuditLogRequest{} }
func (m *GetAuditLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuditLogRequest) ProtoMessage()    {}
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{8}
}

func (m *GetAuditLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuditLogRequest.Unmarshal(m, b)
}
func (m *GetAuditLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuditLogRequest.Marshal(b, m, deterministic)
}
func (m *GetAuditLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuditLogRequest.Merge(m, src)
}
func (m *GetAuditLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuditLogRequest.Size(m)
}
func (m *GetAuditLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuditLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuditLogRequest proto.InternalMessageInfo

func (m *GetAuditLogRequest) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *GetAuditLogRequest) GetSince() *timestamppb.Timestamp {
	if m != nil {
		return m.Since
	}
	return nil
}

func (m *GetAuditLogRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type AuditLogResult struct {
	Events               []*AuditEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AuditLogResult) Reset()         { *m = AuditLogResult{} }
func (m *AuditLogResult) String() string { return proto.CompactTextString(m) }
func (*AuditLogResult) ProtoMessage()    {}
func (*AuditLogResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{9}
}

func (m *AuditLogResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditLogResult.Unmarshal(m, b)
}
func (m *AuditLogResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditLogResult.Marshal(b, m, deterministic)
}
func (m *AuditLogResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditLogResult.Merge(m, src)
}
func (m *AuditLogResult) XXX_Size() int {
	return xxx_messageInfo_AuditLogResult.Size(m)
}
func (m *AuditLogResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditLogResult.DiscardUnknown(m)
}

var xxx_messageInfo_AuditLogResult proto.InternalMessageInfo

func (m *AuditLogResult) GetEvents() []*AuditEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type AuditEvent struct {
	At                   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	EthAddress           string                 `protobuf:"bytes,2,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"`
	Kind                 string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Mode                 ResolveMode            `protobuf:"varint,4,opt,name=mode,proto3,enum=livepeer.registry.v1.ResolveMode" json:"mode,omitempty"`
	Detail               string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AuditEvent) Reset()         { *m = AuditEvent{} }
func (m *AuditEvent) String() string { return proto.CompactTextString(m) }
func (*AuditEvent) ProtoMessage()    {}
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{10}
}

func (m *AuditEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuditEvent.Unmarshal(m, b)
}
func (m *AuditEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuditEvent.Marshal(b, m, deterministic)
}
func (m *AuditEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditEvent.Merge(m, src)
}
func (m *AuditEvent) XXX_Size() int {
	return xxx_messageInfo_AuditEvent.Size(m)
}
func (m *AuditEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AuditEvent proto.InternalMessageInfo

func (m *AuditEvent) GetAt() *timestamppb.Timestamp {
	if m != nil {
		return m.At
	}
	return nil
}

func (m *AuditEvent) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *AuditEvent) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *AuditEvent) GetMode() ResolveMode {
	if m != nil {
		return m.Mode
	}
	return ResolveMode_RESOLVE_MODE_UNSPECIFIED
}

func (m *AuditEvent) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type HealthResult struct {
	Mode                 string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	ChainOk              bool                   `protobuf:"varint,2,opt,name=chain_ok,json=chainOk,proto3" json:"chain_ok,omitempty"`
	ManifestFetcherOk    bool                   `protobuf:"varint,3,opt,name=manifest_fetcher_ok,json=manifestFetcherOk,proto3" json:"manifest_fetcher_ok,omitempty"`
	CacheSize            int32                  `protobuf:"varint,4,opt,name=cache_size,json=cacheSize,proto3" json:"cache_size,omitempty"`
	LastChainSuccess     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_chain_success,json=lastChainSuccess,proto3" json:"last_chain_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HealthResult) Reset()         { *m = HealthResult{} }
func (m *HealthResult) String() string { return proto.CompactTextString(m) }
func (*HealthResult) ProtoMessage()    {}
func (*HealthResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8492eb70280f2d5, []int{11}
}

func (m *HealthResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResult.Unmarshal(m, b)
}
func (m *HealthResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResult.Marshal(b, m, deterministic)
}
func (m *HealthResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResult.Merge(m, src)
}
func (m *HealthResult) XXX_Size() int {
	return xxx_messageInfo_HealthResult.Size(m)
}
func (m *HealthResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResult.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResult proto.InternalMessageInfo

func (m *HealthResult) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *HealthResult) GetChainOk() bool {
	if m != nil {
		return m.ChainOk
	}
	return false
}

func (m *HealthResult) GetManifestFetcherOk() bool {
	if m != nil {
		return m.ManifestFetcherOk
	}
	return false
}

func (m *HealthResult) GetCacheSize() int32 {
	if m != nil {
		return m.CacheSize
	}
	return 0
}

func (m *HealthResult) GetLastChainSuccess() *timestamppb.Timestamp {
	if m != nil {
		return m.LastChainSuccess
	}
	return nil
}

func init() {
	proto.RegisterType((*ResolveByAddressRequest)(nil), "livepeer.registry.v1.ResolveByAddressRequest")
	proto.RegisterType((*ResolveResult)(nil), "livepeer.registry.v1.ResolveResult")
	proto.RegisterType((*SelectRequest)(nil), "livepeer.registry.v1.SelectRequest")
	proto.RegisterType((*SelectResult)(nil), "livepeer.registry.v1.SelectResult")
	proto.RegisterType((*ListKnownRequest)(nil), "livepeer.registry.v1.ListKnownRequest")
	proto.RegisterType((*ListKnownResult)(nil), "livepeer.registry.v1.ListKnownResult")
	proto.RegisterType((*KnownEntry)(nil), "livepeer.registry.v1.KnownEntry")
	proto.RegisterType((*RefreshRequest)(nil), "livepeer.registry.v1.RefreshRequest")
	proto.RegisterType((*GetAuditLogRequest)(nil), "livepeer.registry.v1.GetAuditLogRequest")
	proto.RegisterType((*AuditLogResult)(nil), "livepeer.registry.v1.AuditLogResult")
	proto.RegisterType((*AuditEvent)(nil), "livepeer.registry.v1.AuditEvent")
	proto.RegisterType((*HealthResult)(nil), "livepeer.registry.v1.HealthResult")
}

func init() {
	proto.RegisterFile("livepeer/registry/v1/resolver.proto", fileDescriptor_e8492eb70280f2d5)
}

var fileDescriptor_e8492eb70280f2d5 = []byte{
	// 1053 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xef, 0x6e, 0xdb, 0x36,
	0x10, 0x87, 0x12, 0xdb, 0xb1, 0x2f, 0x71, 0x9a, 0xb1, 0x5d, 0xeb, 0x79, 0xd8, 0xea, 0x2a, 0xcd,
	0x10, 0x0c, 0xb0, 0xdd, 0x64, 0x18, 0xf6, 0xef, 0xcb, 0xd2, 0x2e, 0x49, 0xb1, 0xa6, 0x6b, 0xa7,
	0xac, 0x2b, 0x50, 0x60, 0x10, 0x18, 0xe9, 0x2c, 0x71, 0x96, 0x44, 0x97, 0xa4, 0x1c, 0xb8, 0xc0,
	0x9e, 0x61, 0xcf, 0xb1, 0x57, 0x18, 0xf6, 0x1c, 0x7b, 0x85, 0x7d, 0xdc, 0x2b, 0x0c, 0x22, 0xa9,
	0x38, 0x4d, 0x1c, 0xc7, 0x05, 0xf6, 0x4d, 0xbc, 0xfb, 0xfd, 0x8e, 0xc7, 0xe3, 0xef, 0x8e, 0x82,
	0xcd, 0x84, 0x8d, 0x71, 0x84, 0x28, 0xfa, 0x02, 0x23, 0x26, 0x95, 0x98, 0xf4, 0xc7, 0x3b, 0x7d,
	0x81, 0x92, 0x27, 0x63, 0x14, 0xbd, 0x91, 0xe0, 0x8a, 0x93, 0x5b, 0x25, 0xa8, 0x57, 0x82, 0x7a,
	0xe3, 0x9d, 0xf6, 0x87, 0x11, 0xe7, 0x51, 0x82, 0x7d, 0x8d, 0x39, 0xc9, 0x07, 0x7d, 0x4c, 0x47,
	0x6a, 0x62, 0x28, 0xed, 0xbb, 0x17, 0x9d, 0x8a, 0xa5, 0x28, 0x15, 0x4d, 0x47, 0x16, 0xd0, 0x99,
	0xb9, 0xb1, 0x9a, 0x8c, 0x50, 0x1a, 0x84, 0xfb, 0xa7, 0x03, 0x77, 0x3c, 0x93, 0xc8, 0xc3, 0xc9,
	0x5e, 0x18, 0x0a, 0x94, 0xd2, 0xc3, 0xd7, 0x39, 0x4a, 0x45, 0xee, 0xc2, 0x2a, 0xaa, 0xd8, 0xa7,
	0xc6, 0xda, 0x72, 0x3a, 0xce, 0x76, 0xc3, 0x03, 0x54, 0xb1, 0xc5, 0x91, 0x5d, 0x78, 0x9f, 0x26,
	0x09, 0x3f, 0xf5, 0x13, 0x8c, 0x68, 0x30, 0xf1, 0x07, 0x34, 0x49, 0x4e, 0x68, 0x30, 0x6c, 0x2d,
	0x75, 0x9c, 0xed, 0xba, 0x77, 0x53, 0x3b, 0x8f, 0xb4, 0xef, 0xc0, 0xba, 0xc8, 0x16, 0xac, 0x1b,
	0x4e, 0x9e, 0x49, 0x16, 0x65, 0x18, 0xb6, 0x96, 0x35, 0xb8, 0xa9, 0xad, 0x2f, 0xac, 0x91, 0x6c,
	0x42, 0x73, 0xc0, 0x45, 0x80, 0xbe, 0xc0, 0x81, 0x40, 0x19, 0xb7, 0x2a, 0x1a, 0xb5, 0xa6, 0x8d,
	0x9e, 0xb1, 0xb9, 0x7f, 0x2c, 0x43, 0xd3, 0x26, 0xef, 0xa1, 0xcc, 0x93, 0x05, 0x52, 0xbe, 0x07,
	0x6b, 0xb6, 0xee, 0xa1, 0x9f, 0x0b, 0xa6, 0x33, 0x6d, 0x78, 0xab, 0xa5, 0xed, 0x85, 0x60, 0xe4,
	0x73, 0xa8, 0xa4, 0x3c, 0x44, 0x9d, 0xd7, 0xfa, 0xee, 0xbd, 0xde, 0xac, 0x7b, 0xe9, 0xd9, 0x6d,
	0x9f, 0xf2, 0x10, 0x3d, 0x0d, 0x27, 0x0f, 0xa0, 0x9a, 0xf1, 0x10, 0x65, 0xab, 0xd2, 0x59, 0xde,
	0x5e, 0xdd, 0x6d, 0xcf, 0xe6, 0xfd, 0x50, 0x10, 0x0c, 0x90, 0x3c, 0x87, 0x0d, 0x7d, 0x8e, 0x0c,
	0xa5, 0xf4, 0xa5, 0xa2, 0x2a, 0x97, 0xad, 0xaa, 0xde, 0x74, 0x6b, 0x36, 0xf9, 0xa0, 0x44, 0x1f,
	0x6b, 0xb0, 0x77, 0x63, 0xf0, 0xb6, 0x81, 0x7c, 0x01, 0x8d, 0x80, 0x06, 0x31, 0x86, 0x3e, 0x55,
	0xad, 0x5a, 0xc7, 0xd1, 0x79, 0x18, 0x91, 0xf4, 0x4a, 0x91, 0xf4, 0x7e, 0x2a, 0x45, 0xe2, 0xd5,
	0x0d, 0x78, 0x4f, 0x91, 0xaf, 0x00, 0x06, 0xa8, 0x4a, 0xe6, 0xca, 0xb5, 0xcc, 0x86, 0x45, 0xef,
	0xa9, 0xe2, 0x42, 0x65, 0x10, 0x63, 0x4a, 0xfd, 0x31, 0x0a, 0xc9, 0x78, 0xd6, 0xaa, 0x77, 0x9c,
	0xed, 0xaa, 0xd7, 0x34, 0xd6, 0x9f, 0x8d, 0xd1, 0xfd, 0xc7, 0x81, 0xe6, 0x31, 0x26, 0x18, 0xa8,
	0x52, 0x5e, 0x1f, 0x03, 0x04, 0x74, 0x44, 0x4f, 0x58, 0xc2, 0xd4, 0xa4, 0xbc, 0xaa, 0xa9, 0x85,
	0xdc, 0x82, 0x6a, 0x51, 0xd8, 0xc4, 0xde, 0x91, 0x59, 0x10, 0x02, 0x15, 0xc5, 0x50, 0xe8, 0xdb,
	0x69, 0x78, 0xfa, 0x9b, 0x7c, 0x04, 0x90, 0xb2, 0xcc, 0x3f, 0x45, 0x16, 0xc5, 0x4a, 0x2b, 0xa5,
	0xea, 0x35, 0x52, 0x96, 0xbd, 0xd4, 0x06, 0x72, 0x07, 0x56, 0x22, 0xe4, 0x7e, 0x42, 0x95, 0x2e,
	0xaf, 0xe3, 0xd5, 0x22, 0xe4, 0x47, 0x74, 0xea, 0xe0, 0x99, 0x2e, 0x96, 0x75, 0xf0, 0x8c, 0xb8,
	0xd0, 0x2c, 0x1c, 0xa7, 0x4c, 0xc5, 0x2c, 0xf3, 0x87, 0xa9, 0xae, 0x88, 0xe3, 0xad, 0x46, 0xc8,
	0x5f, 0x6a, 0xdb, 0x93, 0xb4, 0x20, 0xc7, 0x54, 0xfa, 0x11, 0x72, 0x7d, 0xe0, 0xba, 0x57, 0x8b,
	0xa9, 0x3c, 0x44, 0xee, 0x7e, 0x0b, 0x6b, 0xe5, 0x41, 0xb5, 0x26, 0xcf, 0x84, 0xe1, 0x2c, 0x28,
	0x0c, 0x97, 0xc0, 0xc6, 0x11, 0x93, 0xea, 0x49, 0xc6, 0x4f, 0x33, 0x5b, 0x2d, 0xf7, 0x29, 0xdc,
	0x38, 0x67, 0xd3, 0x81, 0xbf, 0x86, 0x15, 0xcc, 0x94, 0x60, 0x67, 0xa1, 0x3b, 0xb3, 0x43, 0x6b,
	0xce, 0x7e, 0xa6, 0xc4, 0xc4, 0x2b, 0x09, 0xee, 0xbf, 0x0e, 0xc0, 0xd4, 0x7e, 0x7d, 0xdf, 0x94,
	0x4d, 0xb1, 0xf4, 0x6e, 0x4d, 0x31, 0x4b, 0xe2, 0xcb, 0xff, 0x9f, 0xc4, 0x2b, 0x8b, 0x4b, 0xdc,
	0x3d, 0x84, 0x75, 0x3b, 0x37, 0x16, 0x9e, 0x6f, 0xb7, 0xa0, 0xaa, 0xe7, 0x8d, 0x9d, 0x67, 0x66,
	0xe1, 0xfe, 0x06, 0xe4, 0x10, 0xd5, 0x5e, 0x1e, 0x32, 0x75, 0xc4, 0xa3, 0x85, 0x83, 0x3d, 0x80,
	0xaa, 0x64, 0x99, 0x0d, 0x36, 0x3f, 0x69, 0x03, 0x2c, 0xb6, 0x4f, 0x58, 0xca, 0x94, 0xae, 0x58,
	0xd5, 0x33, 0x0b, 0xf7, 0x7b, 0x58, 0x9f, 0xee, 0xad, 0x75, 0xf0, 0x25, 0xd4, 0x70, 0x8c, 0x99,
	0xba, 0x46, 0x06, 0x9a, 0xb5, 0x5f, 0x00, 0x3d, 0x8b, 0x77, 0xff, 0x72, 0x00, 0xa6, 0x66, 0xf2,
	0x29, 0x2c, 0x51, 0xa5, 0x53, 0x9f, 0x9f, 0xdf, 0x12, 0xbd, 0x74, 0xde, 0xa5, 0x4b, 0xe7, 0x25,
	0x50, 0x19, 0xb2, 0x2c, 0x2c, 0x1b, 0xb5, 0xf8, 0x3e, 0x53, 0x51, 0xe5, 0xdd, 0x54, 0x74, 0x1b,
	0x6a, 0x21, 0x2a, 0xca, 0x12, 0xdd, 0xbf, 0x0d, 0xcf, 0xae, 0xdc, 0xbf, 0x1d, 0x58, 0x7b, 0x8c,
	0x34, 0x51, 0xb1, 0xad, 0x04, 0xb1, 0xf1, 0x4d, 0xf5, 0x0d, 0xf9, 0x03, 0xa8, 0x07, 0x31, 0x65,
	0x99, 0xcf, 0xcb, 0x77, 0x69, 0x45, 0xaf, 0x9f, 0x0d, 0x49, 0x0f, 0x6e, 0xa6, 0x34, 0x63, 0x03,
	0x94, 0xca, 0x37, 0x03, 0x4d, 0x14, 0x28, 0xf3, 0x20, 0xbd, 0x57, 0xba, 0x0e, 0x8c, 0xe7, 0xd9,
	0xb0, 0x98, 0x33, 0x5a, 0x4e, 0xbe, 0x64, 0x6f, 0xb0, 0x9c, 0x33, 0xda, 0x72, 0xcc, 0xde, 0x20,
	0x79, 0x0c, 0x24, 0xa1, 0x52, 0xf9, 0x66, 0x3b, 0x99, 0x07, 0x41, 0x51, 0x99, 0xea, 0xb5, 0xe5,
	0xdc, 0x28, 0x58, 0x8f, 0x0a, 0xd2, 0xb1, 0xe1, 0xec, 0xfe, 0x5e, 0x81, 0xba, 0x2d, 0x83, 0x20,
	0x03, 0xd8, 0xb8, 0xf8, 0x42, 0x93, 0xee, 0xdc, 0xd2, 0x5d, 0x7c, 0xc9, 0xdb, 0x9b, 0x73, 0xe1,
	0xb6, 0x78, 0x3f, 0x42, 0xcd, 0xcc, 0x2d, 0x72, 0x05, 0xfc, 0xad, 0xf1, 0xdd, 0x76, 0xe7, 0x83,
	0x74, 0xc8, 0x57, 0xd0, 0x38, 0x1b, 0x5a, 0xe4, 0x93, 0xd9, 0x84, 0x8b, 0x93, 0xae, 0xbd, 0x75,
	0x2d, 0x4e, 0xc7, 0x3e, 0x84, 0x15, 0xdb, 0xcf, 0xe4, 0xfe, 0x55, 0xc7, 0x3b, 0xdf, 0xee, 0xed,
	0xdb, 0x97, 0xae, 0x60, 0xbf, 0xf8, 0x97, 0x22, 0xbf, 0xc0, 0xea, 0xb9, 0x7e, 0x26, 0xdb, 0xb3,
	0x83, 0x5d, 0x6e, 0xf9, 0xf6, 0xfd, 0x39, 0x7d, 0x36, 0xed, 0xce, 0xef, 0xa0, 0x66, 0x34, 0x4a,
	0xae, 0x48, 0xe0, 0xaa, 0x4a, 0x9e, 0x57, 0xf6, 0x43, 0xf9, 0xea, 0x75, 0xc4, 0x54, 0x9c, 0x9f,
	0xf4, 0x02, 0x9e, 0xf6, 0x1f, 0x25, 0x3c, 0x0f, 0xbb, 0xc7, 0xcf, 0xf7, 0xfb, 0x25, 0xb3, 0x9b,
	0xf2, 0x30, 0x4f, 0x50, 0x76, 0x47, 0x82, 0xff, 0x8a, 0x81, 0xea, 0x2b, 0x41, 0x33, 0x19, 0xf0,
	0x10, 0xbb, 0xa7, 0x5c, 0x0c, 0x51, 0x74, 0x8b, 0xa7, 0xc5, 0xfc, 0x29, 0xf6, 0x83, 0x84, 0x15,
	0xed, 0xdf, 0x9f, 0xf5, 0x77, 0xf8, 0x4d, 0xf9, 0x3d, 0xde, 0x39, 0xa9, 0x69, 0xf8, 0x67, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xeb, 0x85, 0x56, 0xc0, 0x0a, 0x00, 0x00,
}
