// Code generated by protoc-gen-go. DO NOT EDIT.
// source: livepeer/registry/v1/types.proto

package registryv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ResolveMode mirrors types.ResolveMode in the Go layer. Frozen v1.
type ResolveMode int32

const (
	ResolveMode_RESOLVE_MODE_UNSPECIFIED ResolveMode = 0
	ResolveMode_RESOLVE_MODE_WELL_KNOWN  ResolveMode = 1
	ResolveMode_RESOLVE_MODE_CSV         ResolveMode = 2
	ResolveMode_RESOLVE_MODE_LEGACY      ResolveMode = 3
)

var ResolveMode_name = map[int32]string{
	0: "RESOLVE_MODE_UNSPECIFIED",
	1: "RESOLVE_MODE_WELL_KNOWN",
	2: "RESOLVE_MODE_CSV",
	3: "RESOLVE_MODE_LEGACY",
}

var ResolveMode_value = map[string]int32{
	"RESOLVE_MODE_UNSPECIFIED": 0,
	"RESOLVE_MODE_WELL_KNOWN":  1,
	"RESOLVE_MODE_CSV":         2,
	"RESOLVE_MODE_LEGACY":      3,
}

func (x ResolveMode) String() string {
	return proto.EnumName(ResolveMode_name, int32(x))
}

func (ResolveMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10877c81ef7f22fd, []int{0}
}

// SignatureStatus mirrors types.SignatureStatus.
type SignatureStatus int32

const (
	SignatureStatus_SIGNATURE_STATUS_UNSPECIFIED SignatureStatus = 0
	SignatureStatus_SIGNATURE_STATUS_VERIFIED    SignatureStatus = 1
	SignatureStatus_SIGNATURE_STATUS_UNSIGNED    SignatureStatus = 2
	SignatureStatus_SIGNATURE_STATUS_LEGACY      SignatureStatus = 3
)

var SignatureStatus_name = map[int32]string{
	0: "SIGNATURE_STATUS_UNSPECIFIED",
	1: "SIGNATURE_STATUS_VERIFIED",
	2: "SIGNATURE_STATUS_UNSIGNED",
	3: "SIGNATURE_STATUS_LEGACY",
}

var SignatureStatus_value = map[string]int32{
	"SIGNATURE_STATUS_UNSPECIFIED": 0,
	"SIGNATURE_STATUS_VERIFIED":    1,
	"SIGNATURE_STATUS_UNSIGNED":    2,
	"SIGNATURE_STATUS_LEGACY":      3,
}

func (x SignatureStatus) String() string {
	return proto.EnumName(SignatureStatus_name, int32(x))
}

func (SignatureStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10877c81ef7f22fd, []int{1}
}

// FreshnessStatus mirrors types.FreshnessStatus.
type FreshnessStatus int32

const (
	FreshnessStatus_FRESHNESS_UNSPECIFIED       FreshnessStatus = 0
	FreshnessStatus_FRESHNESS_FRESH             FreshnessStatus = 1
	FreshnessStatus_FRESHNESS_STALE_RECOVERABLE FreshnessStatus = 2
	FreshnessStatus_FRESHNESS_STALE_FAILING     FreshnessStatus = 3
)

var FreshnessStatus_name = map[int32]string{
	0: "FRESHNESS_UNSPECIFIED",
	1: "FRESHNESS_FRESH",
	2: "FRESHNESS_STALE_RECOVERABLE",
	3: "FRESHNESS_STALE_FAILING",
}

var FreshnessStatus_value = map[string]int32{
	"FRESHNESS_UNSPECIFIED":       0,
	"FRESHNESS_FRESH":             1,
	"FRESHNESS_STALE_RECOVERABLE": 2,
	"FRESHNESS_STALE_FAILING":     3,
}

func (x FreshnessStatus) String() string {
	return proto.EnumName(FreshnessStatus_name, int32(x))
}

func (FreshnessStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10877c81ef7f22fd, []int{2}
}

// Source mirrors types.Source.
type Source int32

const (
	Source_SOURCE_UNSPECIFIED    Source = 0
	Source_SOURCE_MANIFEST       Source = 1
	Source_SOURCE_LEGACY         Source = 2
	Source_SOURCE_STATIC_OVERLAY Source = 3
	Source_SOURCE_CSV_FALLBACK   Source = 4
)

var Source_name = map[int32]string{
	0: "SOURCE_UNSPECIFIED",
	1: "SOURCE_MANIFEST",
	2: "SOURCE_LEGACY",
	3: "SOURCE_STATIC_OVERLAY",
	4: "SOURCE_CSV_FALLBACK",
}

var Source_value = map[string]int32{
	"SOURCE_UNSPECIFIED":    0,
	"SOURCE_MANIFEST":       1,
	"SOURCE_LEGACY":         2,
	"SOURCE_STATIC_OVERLAY": 3,
	"SOURCE_CSV_FALLBACK":   4,
}

func (x Source) String() string {
	return proto.EnumName(Source_name, int32(x))
}

func (Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10877c81ef7f22fd, []int{3}
}

// Capability is one named operation a node advertises. The name is
// opaque to the registry; consumers interpret it.
type Capability struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WorkUnit             string   `protobuf:"bytes,2,opt,name=work_unit,json=workUnit,proto3" json:"work_unit,omitempty"`
	Models               []*Model `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	ExtraJson            []byte   `protobuf:"bytes,4,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Capability) Reset()         { *m = Capability{} }
func (m *Capability) String() string { return proto.CompactTextString(m) }
func (*Capability) ProtoMessage()    {}
func (*Capability) Descriptor() ([]byte, []int) {
	return fileDescriptor_10877c81ef7f22fd, []int{0}
}

func (m *Capability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capability.Unmarshal(m, b)
}
func (m *Capability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capability.Marshal(b, m, deterministic)
}
func (m *Capability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capability.Merge(m, src)
}
func (m *Capability) XXX_Size() int {
	return xxx_messageInfo_Capability.Size(m)
}
func (m *Capability) XXX_DiscardUnknown() {
	xxx_messageInfo_Capability.DiscardUnknown(m)
}

var xxx_messageInfo_Capability proto.InternalMessageInfo

func (m *Capability) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Capability) GetWorkUnit() string {
	if m != nil {
		return m.WorkUnit
	}
	return ""
}

func (m *Capability) GetModels() []*Model {
	if m != nil {
		return m.Models
	}
	return nil
}

func (m *Capability) GetExtraJson() []byte {
	if m != nil {
		return m.ExtraJson
	}
	return nil
}

type Model struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PricePerWorkUnitWei  string   `protobuf:"bytes,2,opt,name=price_per_work_unit_wei,json=pricePerWorkUnitWei,proto3" json:"price_per_work_unit_wei,omitempty"`
	Warm                 bool     `protobuf:"varint,3,opt,name=warm,proto3" json:"warm,omitempty"`
	ConstraintsJson      []byte   `protobuf:"bytes,4,opt,name=constraints_json,json=constraintsJson,proto3" json:"constraints_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_10877c81ef7f22fd, []int{1}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetPricePerWorkUnitWei() string {
	if m != nil {
		return m.PricePerWorkUnitWei
	}
	return ""
}

func (m *Model) GetWarm() bool {
	if m != nil {
		return m.Warm
	}
	return false
}

func (m *Model) GetConstraintsJson() []byte {
	if m != nil {
		return m.ConstraintsJson
	}
	return nil
}

// Node is one orchestrator endpoint with resolver-attached metadata.
type Node struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string          `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Lat                  float64         `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64         `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Region               string          `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Capabilities         []*Capability   `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Source               Source          `protobuf:"varint,7,opt,name=source,proto3,enum=livepeer.registry.v1.Source" json:"source,omitempty"`
	SignatureStatus      SignatureStatus `protobuf:"varint,8,opt,name=signature_status,json=signatureStatus,proto3,enum=livepeer.registry.v1.SignatureStatus" json:"signature_status,omitempty"`
	OperatorAddress      string          `protobuf:"bytes,9,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	Enabled              bool            `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TierAllowed          []string        `protobuf:"bytes,11,rep,name=tier_allowed,json=tierAllowed,proto3" json:"tier_allowed,omitempty"`
	Weight               int32           `protobuf:"varint,12,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_10877c81ef7f22fd, []int{2}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Node) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Node) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Node) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Node) GetCapabilities() []*Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *Node) GetSource() Source {
	if m != nil {
		return m.Source
	}
	return Source_SOURCE_UNSPECIFIED
}

func (m *Node) GetSignatureStatus() SignatureStatus {
	if m != nil {
		return m.SignatureStatus
	}
	return SignatureStatus_SIGNATURE_STATUS_UNSPECIFIED
}

func (m *Node) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

func (m *Node) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Node) GetTierAllowed() []string {
	if m != nil {
		return m.TierAllowed
	}
	return nil
}

func (m *Node) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterEnum("livepeer.registry.v1.ResolveMode", ResolveMode_name, ResolveMode_value)
	proto.RegisterEnum("livepeer.registry.v1.SignatureStatus", SignatureStatus_name, SignatureStatus_value)
	proto.RegisterEnum("livepeer.registry.v1.FreshnessStatus", FreshnessStatus_name, FreshnessStatus_value)
	proto.RegisterEnum("livepeer.registry.v1.Source", Source_name, Source_value)
	proto.RegisterType((*Capability)(nil), "livepeer.registry.v1.Capability")
	proto.RegisterType((*Model)(nil), "livepeer.registry.v1.Model")
	proto.RegisterType((*Node)(nil), "livepeer.registry.v1.Node")
}

func init() {
	proto.RegisterFile("livepeer/registry/v1/types.proto", fileDescriptor_10877c81ef7f22fd)
}

var fileDescriptor_10877c81ef7f22fd = []byte{
	// 805 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xd1, 0x6e, 0xdb, 0x36,
	0x14, 0x86, 0x27, 0x3b, 0x71, 0xe3, 0x93, 0xac, 0xd6, 0x98, 0xae, 0x51, 0x97, 0x14, 0xd5, 0x0a,
	0x0c, 0xf0, 0x02, 0xd8, 0x42, 0xda, 0xde, 0xed, 0x4a, 0x51, 0xe8, 0xcc, 0xab, 0x62, 0x07, 0x94,
	0xed, 0xa0, 0xbb, 0x11, 0x64, 0x8b, 0x73, 0xd8, 0xc9, 0xa2, 0x47, 0x52, 0xf6, 0x02, 0x0c, 0xd8,
	0x0b, 0x0c, 0x03, 0xf6, 0x2a, 0x7b, 0xc2, 0x81, 0xb4, 0xdc, 0xd4, 0x89, 0x77, 0x77, 0xf4, 0xfd,
	0xff, 0x11, 0x7f, 0x1e, 0x12, 0x04, 0x37, 0x63, 0x0b, 0x3a, 0xa7, 0x54, 0x78, 0x82, 0x4e, 0x99,
	0x54, 0xe2, 0xce, 0x5b, 0x9c, 0x79, 0xea, 0x6e, 0x4e, 0x65, 0x7b, 0x2e, 0xb8, 0xe2, 0xe8, 0xd9,
	0xda, 0xd1, 0x5e, 0x3b, 0xda, 0x8b, 0xb3, 0x6f, 0x5e, 0x4d, 0x39, 0x9f, 0x66, 0xd4, 0x33, 0x9e,
	0x71, 0xf1, 0x8b, 0xa7, 0xd8, 0x8c, 0x4a, 0x95, 0xcc, 0xe6, 0xab, 0xb6, 0xd7, 0xff, 0x58, 0x00,
	0x41, 0x32, 0x4f, 0xc6, 0x2c, 0x63, 0xea, 0x0e, 0x21, 0xd8, 0xc9, 0x93, 0x19, 0x75, 0x2c, 0xd7,
	0x6a, 0xd6, 0x89, 0xa9, 0xd1, 0x31, 0xd4, 0x97, 0x5c, 0xfc, 0x1a, 0x17, 0x39, 0x53, 0x4e, 0xc5,
	0x08, 0x7b, 0x1a, 0x0c, 0x73, 0xa6, 0xd0, 0x5b, 0xa8, 0xcd, 0x78, 0x4a, 0x33, 0xe9, 0x54, 0xdd,
	0x6a, 0x73, 0xff, 0xcd, 0x71, 0x7b, 0x5b, 0x8e, 0xf6, 0x95, 0xf6, 0x90, 0xd2, 0x8a, 0x5e, 0x02,
	0xd0, 0xdf, 0x95, 0x48, 0xe2, 0x8f, 0x92, 0xe7, 0xce, 0x8e, 0x6b, 0x35, 0x0f, 0x48, 0xdd, 0x90,
	0x9f, 0x24, 0xcf, 0x5f, 0xff, 0x65, 0xc1, 0xae, 0x69, 0x40, 0x4f, 0xa1, 0xc2, 0xd2, 0x32, 0x4c,
	0x85, 0xa5, 0xe8, 0x1d, 0x1c, 0xcd, 0x05, 0x9b, 0xd0, 0x78, 0x4e, 0x45, 0xfc, 0x29, 0x54, 0xbc,
	0xa4, 0xac, 0x0c, 0x76, 0x68, 0xe4, 0x6b, 0x2a, 0x6e, 0xca, 0x80, 0x37, 0x94, 0xe9, 0x4d, 0x2d,
	0x13, 0x31, 0x73, 0xaa, 0xae, 0xd5, 0xdc, 0x23, 0xa6, 0x46, 0xdf, 0x83, 0x3d, 0xe1, 0xb9, 0x54,
	0x22, 0x61, 0xb9, 0x92, 0x9f, 0x07, 0x69, 0x7c, 0xc6, 0x4d, 0x9c, 0x7f, 0xab, 0xb0, 0xd3, 0xe3,
	0x29, 0x7d, 0x94, 0xc6, 0x86, 0x6a, 0x21, 0xb2, 0x72, 0x65, 0x5d, 0x6a, 0x92, 0x25, 0xca, 0x2c,
	0x64, 0x11, 0x5d, 0x1a, 0x52, 0xfe, 0x5a, 0x13, 0x9e, 0xa3, 0xe7, 0x50, 0xd3, 0x93, 0xe1, 0xb9,
	0xb3, 0x6b, 0x1a, 0xcb, 0x2f, 0x74, 0x01, 0x07, 0x93, 0xf5, 0x41, 0x30, 0x2a, 0x9d, 0x9a, 0x99,
	0xa7, 0xbb, 0x7d, 0x9e, 0xf7, 0x47, 0x46, 0x36, 0xba, 0xd0, 0x3b, 0xa8, 0x49, 0x5e, 0x88, 0x09,
	0x75, 0x9e, 0xb8, 0x56, 0xf3, 0xe9, 0x9b, 0x93, 0xed, 0xfd, 0x91, 0xf1, 0x90, 0xd2, 0x8b, 0xae,
	0xc1, 0x96, 0x6c, 0x9a, 0x27, 0xaa, 0x10, 0x34, 0x96, 0x2a, 0x51, 0x85, 0x74, 0xf6, 0x4c, 0xff,
	0x77, 0xff, 0xd3, 0xbf, 0x76, 0x47, 0xc6, 0x4c, 0x1a, 0x72, 0x13, 0xe8, 0xf9, 0xf2, 0x39, 0x15,
	0x89, 0xe2, 0x22, 0x4e, 0xd2, 0x54, 0x50, 0x29, 0x9d, 0xba, 0xd9, 0x6f, 0x63, 0xcd, 0xfd, 0x15,
	0x46, 0x0e, 0x3c, 0xa1, 0x79, 0x32, 0xce, 0x68, 0xea, 0x80, 0x39, 0xa1, 0xf5, 0x27, 0xfa, 0x16,
	0x0e, 0x14, 0xa3, 0x22, 0x4e, 0xb2, 0x8c, 0x2f, 0x69, 0xea, 0xec, 0xbb, 0xd5, 0x66, 0x9d, 0xec,
	0x6b, 0xe6, 0xaf, 0x90, 0x9e, 0xe6, 0x92, 0xb2, 0xe9, 0xad, 0x72, 0x0e, 0x5c, 0xab, 0xb9, 0x4b,
	0xca, 0xaf, 0xd3, 0x25, 0xec, 0x13, 0x2a, 0x79, 0xb6, 0xa0, 0xfa, 0x26, 0xa1, 0x13, 0x70, 0x08,
	0x8e, 0xfa, 0xe1, 0x08, 0xc7, 0x57, 0xfd, 0x0b, 0x1c, 0x0f, 0x7b, 0xd1, 0x35, 0x0e, 0xba, 0x9d,
	0x2e, 0xbe, 0xb0, 0xbf, 0x40, 0xc7, 0x70, 0xb4, 0xa1, 0xde, 0xe0, 0x30, 0x8c, 0xdf, 0xf7, 0xfa,
	0x37, 0x3d, 0xdb, 0x42, 0xcf, 0xc0, 0xde, 0x10, 0x83, 0x68, 0x64, 0x57, 0xd0, 0x11, 0x1c, 0x6e,
	0xd0, 0x10, 0x5f, 0xfa, 0xc1, 0x07, 0xbb, 0x7a, 0xfa, 0xb7, 0x05, 0x8d, 0x07, 0xd3, 0x41, 0x2e,
	0x9c, 0x44, 0xdd, 0xcb, 0x9e, 0x3f, 0x18, 0x12, 0x1c, 0x47, 0x03, 0x7f, 0x30, 0x8c, 0x1e, 0x24,
	0x78, 0x09, 0x2f, 0x1e, 0x39, 0x46, 0x98, 0xac, 0x64, 0x6b, 0xab, 0x3c, 0xec, 0x69, 0x84, 0x2f,
	0xec, 0x8a, 0xce, 0xff, 0x48, 0xfe, 0x14, 0xe8, 0x4f, 0x68, 0x74, 0x04, 0x95, 0xb7, 0x39, 0x95,
	0xb2, 0xcc, 0xf3, 0x02, 0xbe, 0xee, 0x10, 0x1c, 0xfd, 0xd8, 0xc3, 0xd1, 0xc3, 0x20, 0x87, 0xd0,
	0xb8, 0x97, 0x4c, 0x65, 0x5b, 0xe8, 0x15, 0x1c, 0xdf, 0xc3, 0x68, 0xe0, 0x87, 0x38, 0x26, 0x38,
	0xe8, 0x8f, 0x30, 0xf1, 0xcf, 0x43, 0xbc, 0x0a, 0xf0, 0xd0, 0xd0, 0xf1, 0xbb, 0x61, 0xb7, 0x77,
	0x69, 0x57, 0x4f, 0xff, 0x80, 0xda, 0xea, 0xba, 0xa1, 0xe7, 0x80, 0xa2, 0xfe, 0x90, 0x04, 0xf8,
	0xf1, 0xa2, 0x25, 0xbf, 0xf2, 0x7b, 0xdd, 0x0e, 0x8e, 0x06, 0xb6, 0x85, 0xbe, 0x82, 0x2f, 0x4b,
	0x58, 0x6e, 0xa5, 0xa2, 0x73, 0x97, 0x48, 0x6f, 0xb2, 0x1b, 0xc4, 0x3a, 0x42, 0xe8, 0x7f, 0xb0,
	0xab, 0xfa, 0x3c, 0x4a, 0x29, 0x88, 0x46, 0x71, 0xc7, 0x0f, 0xc3, 0x73, 0x3f, 0x78, 0x6f, 0xef,
	0x9c, 0xcb, 0x9f, 0x7f, 0x9b, 0x32, 0x75, 0x5b, 0x8c, 0xdb, 0x13, 0x3e, 0xf3, 0x82, 0x8c, 0x17,
	0x69, 0x2b, 0xba, 0xc6, 0xde, 0xfa, 0x5a, 0xb7, 0x66, 0x3c, 0x2d, 0x32, 0x2a, 0x5b, 0x73, 0xc1,
	0x3f, 0xd2, 0x89, 0xf2, 0x94, 0x48, 0x72, 0x39, 0xe1, 0x29, 0x6d, 0xe9, 0x07, 0x86, 0x8a, 0x56,
	0xce, 0xd3, 0xf2, 0x01, 0xf5, 0x26, 0x19, 0xa3, 0xb9, 0x92, 0xde, 0xb6, 0xd7, 0xf8, 0x87, 0x75,
	0xbd, 0x38, 0x1b, 0xd7, 0x8c, 0xfd, 0xed, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0x95, 0xe2,
	0x63, 0xb7, 0x05, 0x00, 0x00,
}
